#version 450

#include "dequant_head.glsl"

layout(local_size_x = QUANT_K, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {A_TYPE data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

#include "tq_utils.glsl"

void main() {
    const uint ib = gl_WorkGroupID.x;
    const uint tid = gl_LocalInvocationID.x;

    if (ib >= p.nel / QUANT_K) {
        return;
    }

    const float norm = float(data_a[ib].d);

    if (abs(norm) < 1e-15) {
        data_b[ib * QUANT_K + tid] = D_TYPE(0.0);
        return;
    }

    data_b[ib * QUANT_K + tid] = D_TYPE(tbq4_dequant_raw(uint(data_a[ib].qs[tid / 2u]), tid) * norm);
}
