#!/usr/bin/env bash
#
# Test KV cache quantization quality by comparing perplexity across cache types.
# Downloads a small model and wikitext dataset if not already present.
#
# Usage:
#   tests/test-kv-cache-quantization-perp.sh [options] [build_dir]
#
# Options:
#   -c <tiny|tiny2|small|mid|large>  Size config preset (repeatable, default: small)
#   -m <preset>                      Model preset (see -h for list, default: mistral-q4ks)
#   --all                            Run all model presets sequentially
#   --mixed-only                     Skip same-type tests, only run mixed K/V
#   --no-fa                          Disable flash attention (-fa off), uses scalar MUL_MAT fallback
#   --regen-slices                   Regenerate randomized dataset slices even if they already exist
#                                    (default: reuse existing wiki.test.offset_<n_ctx>.raw files so
#                                    reruns are byte-for-byte reproducible)
#   --csv <file>                     Write results to specific CSV file (auto-generated by default)
#   --ks <type> [<type>...]          K cache types to sweep (overrides built-in ALL_CONFIGS)
#   --vs <type> [<type>...]          V cache types to sweep (overrides built-in ALL_CONFIGS)
#                                    When --ks or --vs is given, the Cartesian product is run.
#                                    In --no-fa mode, omitted V types default to f16 because
#                                    quantized V cache requires flash attention.
#   --ref-impl <path>                Reference turboquant repo (default: ../llama-cpp-turboquant, e.g. TheTom)
#   --ref-ks <type> [<type>...]      K cache types from ref impl (default: turbo3 turbo4)
#   --ref-vs <type> [<type>...]      V cache types from ref impl (default: turbo3 turbo4)
#
# Config presets (n_chunks / n_ctx sweep):
#   tiny   — 1 chunk,  n_ctx 64               (single quick check, no stdev)
#   tiny2  — 1 chunk,  n_ctx 64,72            (smoke test with stdev)
#   small  — 2 chunks, n_ctx 64,128           (quick, 2 context sizes)
#   mid    — 4 chunks, n_ctx 448,512          (balanced, near standard 512)
#   large  — 8 chunks, n_ctx 448,512,1024,2048  (thorough, 4 context sizes)
#   huge   — 16 chunks, n_ctx 448,512,1024,2048,4096  (full sweep, 5 context sizes)
#
# Each n_ctx value in the sweep gets its own randomized slice of the dataset,
# so measurements at different context sizes are statistically independent.
# Set DATASET_DIR=wikitext-103-raw for a larger dataset (~100x more text).
#
# Slices are cached on disk as wiki.test.offset_<n_ctx>.raw and reused across
# reruns so PPL numbers are directly comparable when iterating on a fix. Pass
# --regen-slices (or delete the offset files) to force regeneration. Offset
# generation itself uses a fixed $RANDOM seed (SLICE_SEED, default 42), so even
# a fresh regeneration is byte-for-byte reproducible. Export SLICE_SEED=<n>
# to draw a different but still deterministic set of offsets.
#
# WARNING: Presets smaller than 'mid' (tiny, tiny2, small) are prone to statistical noise.
# At very small context sizes, quantization error can occasionally result in lower PPL
# than f16 due to numerical artifacts or the "noise" acting as accidental regularization.
# Use 'mid' or 'large' for reliable quality comparisons.
#
# Perplexity is deterministic — repeating the same run gives identical PPL.
# Instead, presets sweep multiple n_ctx values to measure quality stability
# across context lengths. Mean/stdev are computed across the n_ctx sweep.
#
# Environment variables:
#   MODEL_DIR    — directory for model files (default: models)
#   MODEL_NAME   — GGUF filename
#   MODEL_URL    — download URL
#   CSV          — set to 0 to disable auto CSV output (default: 1)
#   MAX_PPL_REGRESSION_PCT — max allowed PPL regression vs f16 (default: 21)
#
# Examples:
#   tests/test-kv-cache-quantization-perp.sh -c small -c mid --csv ppl.csv
#   tests/test-kv-cache-quantization-perp.sh -c large --csv ppl.csv build
#
set -euo pipefail

# --- Model presets ---

declare -A MODEL_PRESETS_NAME MODEL_PRESETS_URL
MODEL_PRESETS_NAME[mistral-q4ks]="Mistral-7B-Instruct-v0.3-Q4_K_S.gguf"
MODEL_PRESETS_URL[mistral-q4ks]="https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf"
MODEL_PRESETS_NAME[mistral-q4km]="Mistral-7B-Instruct-v0.3-Q4_K_M.gguf"
MODEL_PRESETS_URL[mistral-q4km]="https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf"
MODEL_PRESETS_NAME[mistral-f16]="Mistral-7B-Instruct-v0.3.fp16.gguf"
MODEL_PRESETS_URL[mistral-f16]="https://huggingface.co/MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3.fp16.gguf"
MODEL_PRESETS_NAME[llama-q4km]="Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_URL[llama-q4km]="https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_NAME[llama-f16]="Llama-3.1-8B-Instruct-f16.gguf"
MODEL_PRESETS_URL[llama-f16]="https://huggingface.co/second-state/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Llama-3.1-8B-Instruct-f16.gguf"
MODEL_PRESETS_NAME[qwen-q4km]="Qwen2.5-14B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_URL[qwen-q4km]="https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_NAME[qwen05-q8]="Qwen2.5-0.5B-Instruct-Q8_0.gguf"
MODEL_PRESETS_URL[qwen05-q8]="https://huggingface.co/bartowski/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/Qwen2.5-0.5B-Instruct-Q8_0.gguf"

ALL_MODEL_PRESETS=("mistral-q4km" "mistral-f16" "llama-q4km" "llama-f16" "qwen-q4km" "qwen05-q8")

# --- Parse arguments ---

CONFIGS=()
CSV_FILE=""
BUILD_DIR=""
MIXED_ONLY=false
MODEL_PRESET=""
RUN_ALL=false
FA_FLAG="on"
REF_IMPL=""
REF_KS=()
REF_VS=()
KS=()
VS=()
VS_GIVEN=false

while [ $# -gt 0 ]; do
    case "$1" in
        -c)
            shift
            CONFIGS+=("$1")
            shift
            ;;
        --csv)
            shift
            CSV_FILE="$1"
            shift
            ;;
        --mixed-only)
            MIXED_ONLY=true
            shift
            ;;
        --no-fa)
            FA_FLAG="off"
            shift
            ;;
        --regen-slices)
            REGEN_SLICES=1
            shift
            ;;
        -m)
            shift
            MODEL_PRESET="$1"
            shift
            ;;
        --all)
            RUN_ALL=true
            shift
            ;;
        --ref-impl)
            shift
            REF_IMPL="$1"
            shift
            ;;
        --ref-ks)
            shift
            while [ $# -gt 0 ] && [[ "$1" != -* ]]; do
                REF_KS+=("$1")
                shift
            done
            ;;
        --ref-vs)
            shift
            while [ $# -gt 0 ] && [[ "$1" != -* ]]; do
                REF_VS+=("$1")
                shift
            done
            ;;
        --ks)
            shift
            while [ $# -gt 0 ] && [[ "$1" != -* ]]; do
                KS+=("$1")
                shift
            done
            ;;
        --vs)
            VS_GIVEN=true
            shift
            while [ $# -gt 0 ] && [[ "$1" != -* ]]; do
                VS+=("$1")
                shift
            done
            ;;
        -h|--help)
            head -38 "$0" | tail -37
            echo ""
            echo "Model presets (-m):"
            for k in "${ALL_MODEL_PRESETS[@]}"; do
                echo "  $k  →  ${MODEL_PRESETS_NAME[$k]}"
            done
            echo "  --all runs all presets sequentially"
            echo ""
            echo "Reference implementation (--ref-impl):"
            echo "  --ref-impl <path>  Path to reference repo (default: ../llama-cpp-turboquant)"
            echo "  --ref-ks <types>   K cache types from ref impl (default: turbo3 turbo4)"
            echo "  --ref-vs <types>   V cache types from ref impl (default: turbo3 turbo4)"
            echo "  Rows appear as ref-turbo3, ref-turbo4, etc. (e.g. TheTom's turboquant)"
            exit 0
            ;;
        *)
            BUILD_DIR="$1"
            shift
            ;;
    esac
done

# --- Handle --all: re-exec for each model preset ---

if [ "$RUN_ALL" = true ]; then
    SELF="$0"
    PASS_ARGS=()
    for arg_c in "${CONFIGS[@]}"; do PASS_ARGS+=("-c" "$arg_c"); done
    [ "$MIXED_ONLY" = true ] && PASS_ARGS+=("--mixed-only")
    [ "$FA_FLAG" = "off" ] && PASS_ARGS+=("--no-fa")
    if [ -n "$REF_IMPL" ]; then
        PASS_ARGS+=("--ref-impl" "$REF_IMPL")
    fi
    if [ ${#REF_KS[@]} -gt 0 ]; then
        PASS_ARGS+=("--ref-ks" "${REF_KS[@]}")
    fi
    if [ ${#REF_VS[@]} -gt 0 ]; then
        PASS_ARGS+=("--ref-vs" "${REF_VS[@]}")
    fi
    if [ ${#KS[@]} -gt 0 ]; then
        PASS_ARGS+=("--ks" "${KS[@]}")
    fi
    if [ ${#VS[@]} -gt 0 ]; then
        PASS_ARGS+=("--vs" "${VS[@]}")
    fi
    [ -n "${BUILD_DIR:-}" ] && PASS_ARGS+=("$BUILD_DIR")

    echo "=========================================="
    echo " Running all model presets sequentially"
    echo "=========================================="
    echo ""
    for preset in "${ALL_MODEL_PRESETS[@]}"; do
        echo ">>> Starting: $preset (${MODEL_PRESETS_NAME[$preset]})"
        echo ""
        "$SELF" -m "$preset" "${PASS_ARGS[@]}" || echo ">>> FAILED: $preset"
        echo ""
        echo ">>> Finished: $preset"
        echo ""
    done
    echo "=========================================="
    echo " All model presets complete. Log files:"
    echo "=========================================="
    ls -1t kv-perp_*.txt 2>/dev/null | head -20
    exit 0
fi

BUILD_DIR="${BUILD_DIR:-build}"
PERPLEXITY="$BUILD_DIR/bin/llama-perplexity"

# --- Reference implementation setup ---

REF_PERPLEXITY=""
REF_CONFIGS=()
REF_GIT_INFO=""
REF_GIT_BRANCH=""
REF_GIT_DIRTY=""
REF_GIT_ORIGIN=""

REF_IMPL="${REF_IMPL:-../llama-cpp-turboquant}"
[ ${#REF_KS[@]} -eq 0 ] && REF_KS=("turbo3" "turbo4")
[ ${#REF_VS[@]} -eq 0 ] && REF_VS=("turbo3" "turbo4")

if [ ! -d "$REF_IMPL" ]; then
    echo "Note: reference implementation not found at $REF_IMPL — skipping ref rows."
elif [ ! -f "$REF_IMPL/build/bin/llama-perplexity" ]; then
    echo "Note: reference perplexity binary not found at $REF_IMPL/build/bin/llama-perplexity — skipping ref rows."
else
    REF_PERPLEXITY="$REF_IMPL/build/bin/llama-perplexity"

    for rk in "${REF_KS[@]}"; do
        for rv in "${REF_VS[@]}"; do
            REF_CONFIGS+=("${rk}:${rv}")
        done
    done

    if command -v git &> /dev/null && git -C "$REF_IMPL" rev-parse --git-dir &> /dev/null; then
        REF_GIT_INFO=$(git -C "$REF_IMPL" log --oneline -3 2>/dev/null || true)
        REF_GIT_BRANCH=$(git -C "$REF_IMPL" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
        REF_GIT_DIRTY=$(git -C "$REF_IMPL" diff --quiet 2>/dev/null && echo "" || echo " (dirty)")
        REF_GIT_ORIGIN=$(git -C "$REF_IMPL" remote get-url origin 2>/dev/null || echo "")
    fi

fi

MODEL_DIR="${MODEL_DIR:-models}"

if [ -n "$MODEL_PRESET" ]; then
    if [ -z "${MODEL_PRESETS_NAME[$MODEL_PRESET]:-}" ]; then
        echo "Error: unknown model preset '$MODEL_PRESET'"
        echo "Available: ${ALL_MODEL_PRESETS[*]}"
        exit 1
    fi
    MODEL_NAME="${MODEL_PRESETS_NAME[$MODEL_PRESET]}"
    MODEL_URL="${MODEL_PRESETS_URL[$MODEL_PRESET]}"
else
    MODEL_NAME="${MODEL_NAME:-Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
    MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
fi
MODEL_PATH="$MODEL_DIR/$MODEL_NAME"

# When no -c is given, default to small
if [ ${#CONFIGS[@]} -eq 0 ]; then
    CONFIGS=("tiny2")
fi


DATASET_DIR="${DATASET_DIR:-wikitext-2-raw}"
if [ "$DATASET_DIR" = "wikitext-103-raw" ]; then
    DATASET_FILE="$DATASET_DIR/wiki.test.raw"
    DATASET_ZIP="wikitext-103-raw-v1.zip"
    DATASET_URL="https://huggingface.co/datasets/ggml-org/ci/resolve/main/$DATASET_ZIP"
else
    DATASET_FILE="$DATASET_DIR/wiki.test.raw"
    DATASET_ZIP="wikitext-2-raw-v1.zip"
    DATASET_URL="https://huggingface.co/datasets/ggml-org/ci/resolve/main/$DATASET_ZIP"
fi

MAX_PPL_REGRESSION_PCT="${MAX_PPL_REGRESSION_PCT:-21}"

# Unified config: all K:V pairs in a single list
if [ ${#KS[@]} -gt 0 ] || [ ${#VS[@]} -gt 0 ]; then
    # --ks / --vs override: run the Cartesian product. Missing side defaults to the
    # built-in type list, except under --no-fa where omitted V must stay f16.
    if [ ${#KS[@]} -eq 0 ]; then
        KS=(f16 q8_0 q4_0 pq3_0 pq4_0 tbq3_0 tbq4_0)
    fi
    if [ ${#VS[@]} -eq 0 ]; then
        if [ "$FA_FLAG" = "off" ]; then
            VS=(f16)
        else
            VS=(f16 q8_0 q4_0 pq3_0 pq4_0 tbq3_0 tbq4_0)
        fi
    fi
    if [ "$FA_FLAG" = "off" ] && [ "$VS_GIVEN" = true ]; then
        for vv in "${VS[@]}"; do
            if [ "$vv" != "f16" ]; then
                echo "Error: --no-fa does not support quantized V cache type '$vv' (use --vs f16 or enable flash attention)." >&2
                exit 1
            fi
        done
    fi
    ALL_CONFIGS=()
    for kk in "${KS[@]}"; do
        for vv in "${VS[@]}"; do
            ALL_CONFIGS+=("${kk}:${vv}")
        done
    done
elif [ "$FA_FLAG" = "off" ]; then
    # Without flash attention, only test K quantizations with V=f16
    ALL_CONFIGS=(
        "f16:f16"
        "q8_0:f16"
        "q4_0:f16"
        "pq3_0:f16"
        "pq4_0:f16"
        "tbq3_0:f16"
        "tbq4_0:f16"
    )
else
    ALL_CONFIGS=(
        "f16:f16"
        "q8_0:q8_0"
        "q4_0:q4_0"
        "pq3_0:pq3_0"
        "pq4_0:pq4_0"
        "tbq4_0:pq4_0"
        "tbq3_0:pq3_0"
        "tbq3_0:q4_0"
        "tbq4_0:q4_0"
        "tbq3_0:q8_0"
        "tbq4_0:f16"
        "q8_0:pq3_0"
        "f16:pq4_0"
    )
fi

# --- Config presets ---

config_n_chunks() {
    case "$1" in
        tiny)  echo 1 ;;
        tiny2) echo 1 ;;
        small) echo 2 ;;
        mid)   echo 4 ;;
        large) echo 8 ;;
        huge)  echo 16 ;;
        *) echo "Error: unknown config '$1' (expected tiny, tiny2, small, mid, large, huge)" >&2; exit 1 ;;
    esac
}

config_n_ctx_list() {
    case "$1" in
        tiny)  echo "64" ;;
        tiny2) echo "64 72" ;;
        small) echo "64 128" ;;
        mid)   echo "448 512" ;;
        large) echo "448 512 1024 2048" ;;
        huge)  echo "448 512 1024 2048 4096" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

# --- Download dependencies ---

if [ ! -f "$PERPLEXITY" ]; then
    echo "Error: $PERPLEXITY not found. Build the project first."
    echo "  cmake -B $BUILD_DIR && cmake --build $BUILD_DIR -j\$(nproc)"
    exit 1
fi

mkdir -p "$MODEL_DIR"

if [ ! -f "$MODEL_PATH" ] || [ "$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)" -lt 1000000 ]; then
    [ -f "$MODEL_PATH" ] && rm -f "$MODEL_PATH"
    echo "Downloading model: $MODEL_NAME ..."
    if command -v curl &> /dev/null; then
        curl -L --fail -C - -o "$MODEL_PATH" "$MODEL_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$MODEL_PATH" "$MODEL_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi

    FILE_SIZE=$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [ "$FILE_SIZE" -lt 1000000 ]; then
        echo "Error: downloaded file is only $FILE_SIZE bytes — likely a redirect or error page."
        echo "Download the model manually:"
        echo "  curl -L --fail -o $MODEL_PATH $MODEL_URL"
        rm -f "$MODEL_PATH"
        exit 1
    fi
    echo "Model downloaded to $MODEL_PATH ($((FILE_SIZE / 1048576)) MB)"
else
    echo "Model already exists: $MODEL_PATH"
fi

if [ ! -f "$DATASET_FILE" ]; then
    echo "Downloading wikitext-2 dataset..."
    if command -v curl &> /dev/null; then
        curl -L -o "$DATASET_ZIP" "$DATASET_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$DATASET_ZIP" "$DATASET_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi
    unzip -o "$DATASET_ZIP"
    rm -f "$DATASET_ZIP"
    echo "Dataset extracted to $DATASET_DIR"
else
    echo "Dataset already exists: $DATASET_FILE"
fi

# --- Generate randomized offset slices for each n_ctx ---
# Each n_ctx in the sweep gets its own file starting at a random byte-aligned
# offset into the dataset. This ensures measurements at different context sizes
# are statistically independent (they evaluate different text).

generate_offset_files() {
    local dataset="$1"
    shift
    local ctx_list=("$@")
    local file_size
    file_size=$(stat -c%s "$dataset" 2>/dev/null || stat -f%z "$dataset" 2>/dev/null || echo 0)

    local min_reserve=50000
    local max_offset=$(( file_size - min_reserve ))
    if [ "$max_offset" -lt 0 ]; then
        max_offset=0
    fi

    local offsets=()
    if [ "$max_offset" -gt 0 ]; then
        # Seed $RANDOM so offsets are reproducible across reruns even when the
        # cached slice files are missing (first run, --regen-slices, or another
        # machine). Override by exporting SLICE_SEED before invoking the script
        # when you actually want a fresh random draw.
        RANDOM=${SLICE_SEED:-42}
        for ctx in "${ctx_list[@]}"; do
            offsets+=("$(( RANDOM * 32768 + RANDOM ))")
        done
        # sort and deduplicate to spread them out, then map to range
        local i=0
        for ctx in "${ctx_list[@]}"; do
            local slice_file="${DATASET_DIR}/wiki.test.offset_${ctx}.raw"

            # Reuse existing slice for reproducibility across reruns. The random
            # offset selection is the only non-deterministic step in the script,
            # so keeping the same slices makes PPL numbers directly comparable
            # run-to-run. Delete the offset files (or pass --regen-slices) to
            # force a fresh randomized slice.
            if [ "${REGEN_SLICES:-0}" != "1" ] && [ -s "$slice_file" ]; then
                local slice_size
                slice_size=$(stat -c%s "$slice_file" 2>/dev/null || stat -f%z "$slice_file" 2>/dev/null || echo 0)
                # Recover the original byte offset by subtracting the slice
                # size from the dataset size (slices are always tail suffixes).
                local off_recovered=$(( file_size - slice_size ))
                echo "  n_ctx=$ctx: reusing offset=$off_recovered (${slice_size} bytes) ← $slice_file" >&2
                OFFSET_FILES[$ctx]="$slice_file"
                i=$((i + 1))
                continue
            fi

            local raw_off="${offsets[$i]}"
            local off=$(( raw_off % max_offset ))
            # Align to a newline boundary so we don't start mid-word
            local aligned_off
            aligned_off=$(tail -c +"$((off + 1))" "$dataset" | grep -bom1 $'\n' | head -1 | cut -d: -f1 || echo 0)
            off=$(( off + aligned_off + 1 ))
            if [ "$off" -ge "$file_size" ]; then
                off=0
            fi
            tail -c +"$((off + 1))" "$dataset" > "$slice_file"
            local slice_size
            slice_size=$(stat -c%s "$slice_file" 2>/dev/null || stat -f%z "$slice_file" 2>/dev/null || echo 0)
            echo "  n_ctx=$ctx: offset=$off (${slice_size} bytes) → $slice_file" >&2
            OFFSET_FILES[$ctx]="$slice_file"
            i=$((i + 1))
        done
    else
        for ctx in "${ctx_list[@]}"; do
            OFFSET_FILES[$ctx]="$dataset"
        done
    fi
}

# Collect all unique n_ctx values across all configs
ALL_CTX_VALUES=()
for cfg in "${CONFIGS[@]}"; do
    read -r -a ctx_arr <<< "$(config_n_ctx_list "$cfg")"
    for c in "${ctx_arr[@]}"; do
        ALL_CTX_VALUES+=("$c")
    done
done
# Deduplicate
ALL_CTX_VALUES=($(printf '%s\n' "${ALL_CTX_VALUES[@]}" | sort -un))

declare -A OFFSET_FILES

if [ "${#ALL_CTX_VALUES[@]}" -gt 1 ]; then
    echo ""
    echo "Generating randomized dataset slices for ${#ALL_CTX_VALUES[@]} n_ctx values..."
    generate_offset_files "$DATASET_FILE" "${ALL_CTX_VALUES[@]}"
    echo ""
else
    for c in "${ALL_CTX_VALUES[@]}"; do
        OFFSET_FILES[$c]="$DATASET_FILE"
    done
fi

# --- GPU device detection ---

detect_gpu_device() {
    local gpu_info=""
    local bench_bin="$BUILD_DIR/bin/llama-bench"

    if [ -f "$bench_bin" ]; then
        gpu_info=$("$bench_bin" --list-devices 2>&1 | grep -E '^\s+(Vulkan|CUDA|Metal|SYCL|ROCm)' | head -1 | sed 's/^[[:space:]]*//' || true)
    fi

    if [ -z "$gpu_info" ]; then
        if command -v nvidia-smi &> /dev/null; then
            gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
        elif command -v vulkaninfo &> /dev/null; then
            gpu_info=$(vulkaninfo 2>/dev/null | grep "deviceName" | head -1 | sed 's/.*= //' || true)
        fi
    fi

    echo "${gpu_info:-unknown}"
}

GPU_DEVICE=$(detect_gpu_device)

# Auto-generate CSV filename unless explicitly provided or disabled (CSV=0)
CSV_FINAL=""
if [ -z "$CSV_FILE" ] && [ "${CSV:-1}" != "0" ]; then
    sanitize() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g; s/__*/_/g; s/^_//; s/_$//'; }
    GPU_SHORT=$(echo "$GPU_DEVICE" | sed 's/^[A-Za-z]*[0-9]*: //; s/ ([0-9].*//')
    GPU_TAG=$(sanitize "$GPU_SHORT")
    MODEL_TAG=$(sanitize "${MODEL_NAME%.gguf}")
    CFG_TAG=$(printf '%s-' "${CONFIGS[@]}" | sed 's/-$//')
    CSV_FILE="kv-perp_${GPU_TAG}_${MODEL_TAG}_${CFG_TAG}_$(date +%Y%m%d_%H%M%S).csv"
fi
if [ -n "$CSV_FILE" ]; then
    CSV_FINAL="$CSV_FILE"
    CSV_FILE=$(mktemp /tmp/kv-perp-XXXXXX.csv)
fi

# --- Log file setup (same name as CSV, .txt extension) ---

LOG_FILE=""
if [ -n "$CSV_FINAL" ]; then
    LOG_FILE="${CSV_FINAL%.csv}.txt"
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

# --- Bits per value (theoretical) ---

get_bpw() {
    case "$1" in
        f16)     echo "16.00" ;;
        q8_0)    echo "8.50"  ;;
        q4_0)    echo "4.50"  ;;
        q4_1)    echo "5.00"  ;;
        q5_0)    echo "5.50"  ;;
        q5_1)    echo "6.00"  ;;
        q2_K)    echo "2.625" ;;
        q3_K)    echo "3.44"  ;;
        q4_K)    echo "4.50"  ;;
        q5_K)    echo "5.50"  ;;
        q6_K)    echo "6.56"  ;;
        iq2_xxs) echo "2.06"  ;;
        iq2_xs)  echo "2.31"  ;;
        iq2_s)   echo "2.50"  ;;
        iq3_xxs) echo "3.06"  ;;
        iq3_s)   echo "3.44"  ;;
        pq3_0)   echo "3.25"  ;;
        pq4_0)   echo "4.25"  ;;
        tbq3_0)  echo "4.25"  ;;
        tbq4_0)  echo "5.25"  ;;
        *)       echo "0.00"  ;;
    esac
}

# --- Perplexity extraction ---

extract_ppl_and_sd() {
    local output="$1"
    local line
    line=$(echo "$output" | grep 'PPL = ' | tail -1)
    local ppl sd
    ppl=$(echo "$line" | sed -n 's/.*PPL = \([0-9.]*\).*/\1/p')
    sd=$(echo "$line" | sed -n 's/.*+\/- \([0-9.]*\).*/\1/p')
    sd="${sd:-0.0000}"
    echo "$ppl $sd"
}

# --- CSV setup ---

CSV_ROWS=()

csv_init() {
    if [ -n "$CSV_FILE" ]; then
        echo "gpu_device,model,config,cache_k,cache_v,mixed,norm_correction,bpw_avg,n_chunks,n_ctx_sweep,ppl_mean,ppl_sweep_sd,ppl_chunk_sd,time_mean_s,time_stdev_s,ppl_vs_f16_pct,ppl_vs_f16_pct_stdev,time_vs_f16_x,time_vs_f16_x_stdev" > "$CSV_FILE"
    fi
}

NC_FLAG="off"

csv_append() {
    local k_type="$1" v_type="$2" is_mixed="$3" n_chunks="$4" n_ctx_sweep="$5"
    local ppl_mean="$6" ppl_sweep_sd="$7" ppl_chunk_sd="$8" time_mean="$9" time_sd="${10}"
    local ppl_vs_f16="${11}" ppl_vs_f16_sd="${12}" time_vs_f16="${13}" time_vs_f16_sd="${14}" config_name="${15}"
    local bpw_k=$(get_bpw "$k_type")
    local bpw_v=$(get_bpw "$v_type")
    local bpw_avg=$(echo "$bpw_k $bpw_v" | awk '{printf "%.2f", ($1 + $2) / 2}')
    local row="\"$GPU_DEVICE\",\"$MODEL_NAME\",\"$config_name\",\"$k_type\",\"$v_type\",\"$is_mixed\",\"$NC_FLAG\",$bpw_avg,$n_chunks,\"$n_ctx_sweep\",$ppl_mean,$ppl_sweep_sd,$ppl_chunk_sd,$time_mean,$time_sd,$ppl_vs_f16,$ppl_vs_f16_sd,$time_vs_f16,$time_vs_f16_sd"
    CSV_ROWS+=("$row")
    if [ -n "$CSV_FILE" ]; then
        echo "$row" >> "$CSV_FILE"
    fi
}

csv_init

# --- Git info ---

GIT_INFO=""
if command -v git &> /dev/null && git rev-parse --git-dir &> /dev/null; then
    GIT_INFO=$(git log --oneline -3 2>/dev/null || true)
    GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    GIT_DIRTY=$(git diff --quiet 2>/dev/null && echo "" || echo " (dirty)")
    GIT_ORIGIN=$(git remote get-url origin 2>/dev/null || echo "")
fi

# --- Print header ---

echo ""
echo "=========================================="
echo " KV Cache Quantization Perplexity Test"
echo "=========================================="
if [ -n "$GIT_INFO" ]; then
    [ -n "$GIT_ORIGIN" ] && echo " Origin:   $GIT_ORIGIN"
    echo " Branch:   ${GIT_BRANCH}${GIT_DIRTY}"
    echo "$GIT_INFO" | while IFS= read -r line; do
        echo "           $line"
    done
fi
echo " GPU:      $GPU_DEVICE"
echo " Model:    $MODEL_NAME"
echo " Dataset:  $DATASET_FILE"
echo " Configs:  ${CONFIGS[*]}"
for cfg_info in "${CONFIGS[@]}"; do
    local_chunks=$(config_n_chunks "$cfg_info")
    local_ctx_list=$(config_n_ctx_list "$cfg_info")
    echo "   $cfg_info: chunks=$local_chunks n_ctx=[$local_ctx_list]"
done
echo " α-scale:  on (TBQ/PQ types compared with MSE-optimal norm correction)"
if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
    echo " ──────────────────────────────────────"
    echo " Ref impl: $(readlink -f "$REF_IMPL") "
    echo " Ref bin:  $REF_PERPLEXITY"
    if [ -n "$REF_GIT_INFO" ]; then
        [ -n "$REF_GIT_ORIGIN" ] && echo " Ref origin: $REF_GIT_ORIGIN"
        echo " Ref branch: ${REF_GIT_BRANCH}${REF_GIT_DIRTY}"
        echo "$REF_GIT_INFO" | while IFS= read -r line; do
            echo "             $line"
        done
    fi
    echo " Ref K types: ${REF_KS[*]}"
    echo " Ref V types: ${REF_VS[*]}"
    echo " Ref configs: ${REF_CONFIGS[*]}"
fi
if [ -n "$CSV_FINAL" ]; then
    echo " CSV:      $CSV_FINAL"
    echo " Log:      $LOG_FILE"
fi
echo "=========================================="
echo ""

# --- Helper: run perplexity once ---

run_perplexity_once() {
    local k_type="$1" v_type="$2" n_ctx="$3" n_chunks="$4"
    local bin="${5:-$PERPLEXITY}"

    local env_prefix=""
    if [ "${GGML_TQ_NORM_CORRECTION:-0}" = "1" ]; then
        env_prefix="GGML_TQ_NORM_CORRECTION=1 "
    fi

    local chunks_args=""
    if [ "$n_chunks" -gt 0 ]; then
        chunks_args="--chunks $n_chunks"
    fi

    # Use offset file for this n_ctx if available
    local data_file="${OFFSET_FILES[$n_ctx]:-$DATASET_FILE}"

    # Force single-GPU execution so PPL is reproducible across hosts. Without
    # --split-mode none, llama-perplexity defaults to splitting decoder layers
    # across all visible devices, which introduces cross-device numerical
    # differences that can drift the baseline by more than the QJL/FA signal
    # we're looking for. Matches the default in test-kv-cache-quantization-perf.sh.
    echo "  \$ ${env_prefix}${bin} \\" >&2
    echo "      -m $MODEL_PATH \\" >&2
    echo "      -f $data_file \\" >&2
    echo "      --cache-type-k $k_type --cache-type-v $v_type \\" >&2
    echo "      --split-mode none \\" >&2
    echo "      -fa $FA_FLAG -n $n_ctx ${chunks_args}" >&2

    local start_time end_time elapsed_ms elapsed_s output ppl

    start_time=$(date +%s%N)

    # shellcheck disable=SC2086
    output=$("$bin" \
        -m "$MODEL_PATH" \
        -f "$data_file" \
        --cache-type-k "$k_type" \
        --cache-type-v "$v_type" \
        --split-mode none \
        -fa "$FA_FLAG" \
        -n "$n_ctx" \
        $chunks_args \
        2>&1) || {
        echo "FAILED" >&2
        echo "$output" | tail -10 >&2
        return 1
    }

    end_time=$(date +%s%N)
    elapsed_ms=$(( (end_time - start_time) / 1000000 ))
    elapsed_s=$(echo "$elapsed_ms" | awk '{printf "%.2f", $1/1000}')

    local ppl_sd_pair
    ppl_sd_pair=$(extract_ppl_and_sd "$output")
    ppl=$(echo "$ppl_sd_pair" | awk '{print $1}')
    local ppl_sd
    ppl_sd=$(echo "$ppl_sd_pair" | awk '{print $2}')
    if [ -z "$ppl" ]; then
        echo "PARSE_FAILED" >&2
        echo "$output" | tail -10 >&2
        return 1
    fi

    echo "$ppl $ppl_sd $elapsed_s"
}

# --- Helper: run across n_ctx values, compute mean and stdev ---

run_perplexity_sweep() {
    local k_type="$1" v_type="$2" n_chunks="$3"
    shift 3
    local ctx_list=("$@")
    local n_runs=${#ctx_list[@]}

    local ppls=() ppl_sds=() times=()

    for (( i=0; i<n_runs; i++ )); do
        local ctx="${ctx_list[$i]}"
        local result
        result=$(run_perplexity_once "$k_type" "$v_type" "$ctx" "$n_chunks" "${SWEEP_BIN:-}") || return 1
        local ppl_val ppl_sd_val time_val
        ppl_val=$(echo "$result" | awk '{print $1}')
        ppl_sd_val=$(echo "$result" | awk '{print $2}')
        time_val=$(echo "$result" | awk '{print $3}')
        ppls+=("$ppl_val")
        ppl_sds+=("$ppl_sd_val")
        times+=("$time_val")
        if [ "$n_runs" -gt 1 ]; then
            echo "    n_ctx=$ctx: PPL=${ppl_val}±${ppl_sd_val} (${time_val}s)" >&2
        fi
    done

    local ppl_mean ppl_sweep_sd ppl_chunk_sd time_mean time_stdev
    if [ "$n_runs" -eq 1 ]; then
        ppl_mean="${ppls[0]}"
        ppl_sweep_sd="0.0000"
        ppl_chunk_sd="${ppl_sds[0]}"
        time_mean="${times[0]}"
        time_stdev="0.00"
    else
        ppl_mean=$(printf '%s\n' "${ppls[@]}" | awk '{s+=$1; n++} END {printf "%.4f", s/n}')
        ppl_sweep_sd=$(printf '%s\n' "${ppls[@]}" | awk -v mean="$ppl_mean" '{d=$1-mean; ss+=d*d; n++} END {printf "%.4f", sqrt(ss/(n-1))}')
        ppl_chunk_sd=$(printf '%s\n' "${ppl_sds[@]}" | awk '{s+=$1*$1; n++} END {printf "%.4f", sqrt(s/n)}')
        time_mean=$(printf '%s\n' "${times[@]}" | awk '{s+=$1; n++} END {printf "%.2f", s/n}')
        time_stdev=$(printf '%s\n' "${times[@]}" | awk -v mean="$time_mean" '{d=$1-mean; ss+=d*d; n++} END {printf "%.2f", sqrt(ss/(n-1))}')
    fi

    # Output: ppl_mean sweep_sd chunk_sd time_mean time_stdev
    echo "$ppl_mean $ppl_sweep_sd $ppl_chunk_sd $time_mean $time_stdev"
}

# --- Main benchmark loop over configs ---

num_failed=0

# TBQ/PQ types that are affected by norm correction
is_tq_type() {
    case "$1" in
        tbq3_0|tbq4_0|pq3_0|pq4_0) return 0 ;;
        *) return 1 ;;
    esac
}

is_mixed() {
    local k="$1" v="$2"
    [ "$k" != "$v" ]
}

for cfg in "${CONFIGS[@]}"; do
    N_CHUNKS_CFG=$(config_n_chunks "$cfg")
    read -r -a N_CTX_LIST <<< "$(config_n_ctx_list "$cfg")"
    N_RUNS=${#N_CTX_LIST[@]}
    HAS_STDEV=1

    echo ""
    echo "############################################"
    echo " Config: $cfg  (chunks=$N_CHUNKS_CFG, n_ctx=[${N_CTX_LIST[*]}])"
    echo "############################################"
    echo ""

    declare -A ppl_results ppl_sweep_sd_results ppl_chunk_sd_results time_results time_sd_results
    declare -A ppl_results_a ppl_sweep_sd_results_a ppl_chunk_sd_results_a time_results_a time_sd_results_a

    # --- Helper: format value±sd (only shows ± when HAS_STDEV) ---
    fmt_pm() { [ "$HAS_STDEV" -eq 1 ] && echo "${1}±${2}" || echo "$1"; }

    fmt_regression() {
        local ppl="$1" ppl_sd="$2" base="$3"
        local reg reg_sd
        reg=$(echo "$ppl $base" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
        if [ "$HAS_STDEV" -eq 1 ]; then
            reg_sd=$(echo "$ppl_sd $base" | awk '{printf "%.2f", ($1 / $2) * 100}')
            printf "%+.2f±%s%%" "$reg" "$reg_sd"
        else
            printf "%+.2f%%" "$reg"
        fi
    }

    fmt_slowdown() {
        local t="$1" t_sd="$2" base_t="$3" base_t_sd="$4"
        local ratio ratio_sd
        ratio=$(echo "$t $base_t" | awk '{if ($2 > 0) printf "%.1f", $1/$2; else {print "n/a"; exit}}')
        if [ "$HAS_STDEV" -eq 1 ]; then
            ratio_sd=$(echo "$t $t_sd $base_t $base_t_sd" | awk '{
                if ($3 > 0) {
                    a = ($2/$3)^2; b = ($1*$4/($3*$3))^2;
                    printf "%.1f", sqrt(a+b)
                } else print "0.0"
            }')
            echo "${ratio}±${ratio_sd}x"
        else
            echo "${ratio}x"
        fi
    }

    # --- Determine which configs to run ---

    RUN_CONFIGS=()
    for pair in "${ALL_CONFIGS[@]}"; do
        k_type="${pair%%:*}"
        v_type="${pair##*:}"
        if [ "$MIXED_ONLY" = true ] && [ "$k_type" = "$v_type" ] && [ "$k_type" != "f16" ]; then
            continue
        fi
        RUN_CONFIGS+=("$pair")
    done

    # --- Count total jobs for ETA ---

    total_jobs=0
    for pair in "${RUN_CONFIGS[@]}"; do
        total_jobs=$((total_jobs + 1))
        k_type="${pair%%:*}"; v_type="${pair##*:}"
        if is_tq_type "$k_type" || is_tq_type "$v_type"; then
            total_jobs=$((total_jobs + 1))
        fi
    done
    if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
        total_jobs=$((total_jobs + ${#REF_CONFIGS[@]}))
    fi
    completed_jobs=0
    bench_start_time=$(date +%s)

    fmt_eta() {
        local done="$1" total="$2" start="$3"
        if [ "$done" -eq 0 ]; then echo "estimating..."; return; fi
        local now elapsed avg remaining
        now=$(date +%s)
        elapsed=$((now - start))
        avg=$((elapsed / done))
        remaining=$(( avg * (total - done) ))
        if [ "$remaining" -ge 3600 ]; then
            printf "%dh%02dm" $((remaining/3600)) $(( (remaining%3600)/60 ))
        elif [ "$remaining" -ge 60 ]; then
            printf "%dm%02ds" $((remaining/60)) $((remaining%60))
        else
            printf "%ds" "$remaining"
        fi
    }

    # --- Run all configs ---

    export GGML_TQ_NORM_CORRECTION=0
    for pair in "${RUN_CONFIGS[@]}"; do
        k_type="${pair%%:*}"
        v_type="${pair##*:}"

        bpw_k=$(get_bpw "$k_type")
        bpw_v=$(get_bpw "$v_type")
        bpw_avg=$(echo "$bpw_k $bpw_v" | awk '{printf "%.2f", ($1 + $2) / 2}')

        eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
        echo "--- [$((completed_jobs+1))/$total_jobs, ETA $eta] Running perplexity with K=$k_type V=$v_type [$cfg] (BPW=$bpw_avg) ---"

        result=$(run_perplexity_sweep "$k_type" "$v_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
            echo "FAILED: perplexity run crashed for K=$k_type V=$v_type"
            exit 1
        }

        ppl_results["$pair"]=$(echo "$result" | awk '{print $1}')
        ppl_sweep_sd_results["$pair"]=$(echo "$result" | awk '{print $2}')
        ppl_chunk_sd_results["$pair"]=$(echo "$result" | awk '{print $3}')
        time_results["$pair"]=$(echo "$result" | awk '{print $4}')
        time_sd_results["$pair"]=$(echo "$result" | awk '{print $5}')
        completed_jobs=$((completed_jobs + 1))
        echo "  K=$k_type V=$v_type PPL = ${ppl_results[$pair]} (sweep±${ppl_sweep_sd_results[$pair]}, chunk±${ppl_chunk_sd_results[$pair]})  ($(fmt_pm "${time_results[$pair]}" "${time_sd_results[$pair]}")s)"
        echo ""

        if is_tq_type "$k_type" || is_tq_type "$v_type"; then
            eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
            echo "--- [$((completed_jobs+1))/$total_jobs, ETA $eta] Running perplexity with K=$k_type V=$v_type [$cfg] (α, BPW=$bpw_avg) ---"
            export GGML_TQ_NORM_CORRECTION=1
            result=$(run_perplexity_sweep "$k_type" "$v_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
                echo "FAILED: perplexity run crashed for K=$k_type V=$v_type (α)"
                exit 1
            }
            export GGML_TQ_NORM_CORRECTION=0
            ppl_results_a["$pair"]=$(echo "$result" | awk '{print $1}')
            ppl_sweep_sd_results_a["$pair"]=$(echo "$result" | awk '{print $2}')
            ppl_chunk_sd_results_a["$pair"]=$(echo "$result" | awk '{print $3}')
            time_results_a["$pair"]=$(echo "$result" | awk '{print $4}')
            time_sd_results_a["$pair"]=$(echo "$result" | awk '{print $5}')
            completed_jobs=$((completed_jobs + 1))
            echo "  K=$k_type V=$v_type (α) PPL = ${ppl_results_a[$pair]} (sweep±${ppl_sweep_sd_results_a[$pair]}, chunk±${ppl_chunk_sd_results_a[$pair]})  ($(fmt_pm "${time_results_a[$pair]}" "${time_sd_results_a[$pair]}")s)"
            echo ""
        fi
    done

    # --- Run reference implementation configs ---

    if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
        export GGML_TQ_NORM_CORRECTION=0
        SWEEP_BIN="$REF_PERPLEXITY"
        for pair in "${REF_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            ref_key="ref-${k_type}:ref-${v_type}"

            eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
            echo "--- [$((completed_jobs+1))/$total_jobs, ETA $eta] Running perplexity with K=ref-$k_type V=ref-$v_type [$cfg] (ref impl) ---"

            result=$(run_perplexity_sweep "$k_type" "$v_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
                echo "FAILED: ref perplexity run crashed for K=$k_type V=$v_type"
                continue
            }

            ppl_results["$ref_key"]=$(echo "$result" | awk '{print $1}')
            ppl_sweep_sd_results["$ref_key"]=$(echo "$result" | awk '{print $2}')
            ppl_chunk_sd_results["$ref_key"]=$(echo "$result" | awk '{print $3}')
            time_results["$ref_key"]=$(echo "$result" | awk '{print $4}')
            time_sd_results["$ref_key"]=$(echo "$result" | awk '{print $5}')
            completed_jobs=$((completed_jobs + 1))
            echo "  K=ref-$k_type V=ref-$v_type PPL = ${ppl_results[$ref_key]} (sweep±${ppl_sweep_sd_results[$ref_key]}, chunk±${ppl_chunk_sd_results[$ref_key]})  ($(fmt_pm "${time_results[$ref_key]}" "${time_sd_results[$ref_key]}")s)"
            echo ""
        done
        unset SWEEP_BIN
    fi

    # --- Print unified summary ---

    baseline_ppl="${ppl_results[f16:f16]}"
    # baseline_ppl_sd="${ppl_sd_results[f16:f16]}"
    baseline_time="${time_results[f16:f16]}"
    baseline_time_sd="${time_sd_results[f16:f16]}"

    echo ""
    echo "=========================================="
    echo " Results Summary [$cfg]"
    echo "=========================================="
    printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
        "K type" "V type" "BPW" "PPL" "sweep±" "chunk±" "vs f16" "Time"
    printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
        "------" "------" "---" "---" "-------" "------" "------" "----"

    for pair in "${RUN_CONFIGS[@]}"; do
        k_type="${pair%%:*}"
        v_type="${pair##*:}"
        ppl="${ppl_results[$pair]}"
        sweep_sd="${ppl_sweep_sd_results[$pair]}"
        chunk_sd="${ppl_chunk_sd_results[$pair]}"
        elapsed="${time_results[$pair]}"
        elapsed_sd="${time_sd_results[$pair]}"

        bpw_k=$(get_bpw "$k_type")
        bpw_v=$(get_bpw "$v_type")
        bpw_avg=$(echo "$bpw_k $bpw_v" | awk '{printf "%.2f", ($1 + $2) / 2}')

        time_disp="$(fmt_pm "$elapsed" "$elapsed_sd")s"

        if [ "$pair" = "f16:f16" ]; then
            printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
                "$k_type" "$v_type" "$bpw_avg" "$ppl" "$sweep_sd" "$chunk_sd" "(baseline)" "$time_disp"
        else
            reg_disp=$(fmt_regression "$ppl" "$sweep_sd" "$baseline_ppl")
            printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
                "$k_type" "$v_type" "$bpw_avg" "$ppl" "$sweep_sd" "$chunk_sd" "$reg_disp" "$time_disp"
        fi

        if [ -n "${ppl_results_a[$pair]:-}" ]; then
            ppl_a="${ppl_results_a[$pair]}"
            sweep_sd_a="${ppl_sweep_sd_results_a[$pair]}"
            chunk_sd_a="${ppl_chunk_sd_results_a[$pair]}"
            elapsed_a="${time_results_a[$pair]}"
            elapsed_sd_a="${time_sd_results_a[$pair]}"
            time_disp_a="$(fmt_pm "$elapsed_a" "$elapsed_sd_a")s"
            reg_disp_a=$(fmt_regression "$ppl_a" "$sweep_sd_a" "$baseline_ppl")
            printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
                "  └ α" "" "-" "$ppl_a" "$sweep_sd_a" "$chunk_sd_a" "$reg_disp_a" "$time_disp_a"
        fi
    done

    if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
        printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
            "---ref---" "---ref---" "---" "---" "-------" "------" "------" "----"
        for pair in "${REF_CONFIGS[@]}"; do
            ref_key="ref-${pair%%:*}:ref-${pair##*:}"
            [ -z "${ppl_results[$ref_key]:-}" ] && continue
            k_disp="ref-${pair%%:*}"
            v_disp="ref-${pair##*:}"
            ppl="${ppl_results[$ref_key]}"
            sweep_sd="${ppl_sweep_sd_results[$ref_key]}"
            chunk_sd="${ppl_chunk_sd_results[$ref_key]}"
            elapsed="${time_results[$ref_key]}"
            elapsed_sd="${time_sd_results[$ref_key]}"

            time_disp="$(fmt_pm "$elapsed" "$elapsed_sd")s"
            reg_disp=$(fmt_regression "$ppl" "$sweep_sd" "$baseline_ppl")
            printf "  %-10s %-10s %-6s %10s %10s %10s %14s %10s\n" \
                "$k_disp" "$v_disp" "-" "$ppl" "$sweep_sd" "$chunk_sd" "$reg_disp" "$time_disp"
        done
    fi

    echo "  --"
    echo "  sweep± = stdev across n_ctx values (different text offsets)"
    echo "  chunk± = mean within-file stdev (from llama-perplexity)"
    echo "  └ α    = MSE-optimal norm correction for TBQ/PQ types"
    echo "=========================================="

    # --- Check regressions ---

    for pair in "${RUN_CONFIGS[@]}"; do
        [ "$pair" = "f16:f16" ] && continue

        ppl="${ppl_results[$pair]}"
        exceeded=$(echo "$ppl $baseline_ppl $MAX_PPL_REGRESSION_PCT" | \
            awk '{regression = (($1 - $2) / $2) * 100; print (regression > $3) ? "1" : "0"}')

        if [ "$exceeded" = "1" ]; then
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            regression=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
            echo "FAILED: K=$k_type V=$v_type PPL regression ${regression}% exceeds ${MAX_PPL_REGRESSION_PCT}% threshold"
            num_failed=$((num_failed + 1))
        fi
    done

    if [ "$MIXED_ONLY" = false ]; then
    pq3_ppl="${ppl_results[pq3_0:pq3_0]}"
    pq4_ppl="${ppl_results[pq4_0:pq4_0]}"
    pq4_worse=$(echo "$pq4_ppl $pq3_ppl" | awk '{print ($1 > $2) ? "1" : "0"}')
    if [ "$pq4_worse" = "1" ]; then
        echo "FAILED: pq4_0 PPL ($pq4_ppl) should be <= pq3_0 PPL ($pq3_ppl)"
        num_failed=$((num_failed + 1))
    fi

    tbq4pq4_ppl="${ppl_results[tbq4_0:pq4_0]}"
    tbq4pq4_worse=$(echo "$tbq4pq4_ppl $pq4_ppl" | awk '{print ($1 > $2) ? "1" : "0"}')
    if [ "$tbq4pq4_worse" = "1" ]; then
        echo "WARNING: tbq4_0:pq4_0 PPL ($tbq4pq4_ppl) should be <= pq4_0:pq4_0 PPL ($pq4_ppl)"
    fi
    tbq3pq3_ppl="${ppl_results[tbq3_0:pq3_0]}"
    tbq3pq3_worse=$(echo "$tbq3pq3_ppl $pq3_ppl" | awk '{print ($1 > $2) ? "1" : "0"}')
    if [ "$tbq3pq3_worse" = "1" ]; then
        echo "WARNING: tbq3_0:pq3_0 PPL ($tbq3pq3_ppl) should be <= pq3_0:pq3_0 PPL ($pq3_ppl)"
    fi
    fi

    # --- Write CSV rows ---

    CTX_SWEEP_STR="${N_CTX_LIST[*]}"

    if [ -n "$CSV_FILE" ]; then
        csv_regression_sd() {
            echo "$1 $2" | awk '{printf "%.2f", ($1 / $2) * 100}'
        }
        csv_ratio_sd() {
            echo "$1 $2 $3 $4" | awk '{
                if ($3 > 0) {
                    a = ($2/$3)^2; b = ($1*$4/($3*$3))^2;
                    printf "%.2f", sqrt(a+b)
                } else print ""
            }'
        }

        NC_FLAG="off"
        for pair in "${RUN_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            ppl="${ppl_results[$pair]}"
            sweep_sd="${ppl_sweep_sd_results[$pair]}"
            chunk_sd="${ppl_chunk_sd_results[$pair]}"
            elapsed="${time_results[$pair]}"
            elapsed_sd="${time_sd_results[$pair]}"
            is_m="no"
            [ "$k_type" != "$v_type" ] && is_m="yes"
            if [ "$pair" = "f16:f16" ]; then
                ppl_vs_f16="0.00"
                ppl_vs_f16_sd="0.00"
                time_vs_f16="1.00"
                time_vs_f16_sd="0.00"
            else
                ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
                ppl_vs_f16_sd=$(csv_regression_sd "$sweep_sd" "$baseline_ppl")
                time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
                time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
            fi
            csv_append "$k_type" "$v_type" "$is_m" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$sweep_sd" "$chunk_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg"
        done

        NC_FLAG="on"
        for pair in "${RUN_CONFIGS[@]}"; do
            [ -z "${ppl_results_a[$pair]:-}" ] && continue
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            ppl="${ppl_results_a[$pair]}"
            sweep_sd="${ppl_sweep_sd_results_a[$pair]}"
            chunk_sd="${ppl_chunk_sd_results_a[$pair]}"
            elapsed="${time_results_a[$pair]}"
            elapsed_sd="${time_sd_results_a[$pair]}"
            is_m="no"
            [ "$k_type" != "$v_type" ] && is_m="yes"
            ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
            ppl_vs_f16_sd=$(csv_regression_sd "$sweep_sd" "$baseline_ppl")
            time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
            time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
            csv_append "$k_type" "$v_type" "$is_m" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$sweep_sd" "$chunk_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg"
        done
        NC_FLAG="off"

        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            NC_FLAG="off"
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                [ -z "${ppl_results[$ref_key]:-}" ] && continue
                k_disp="ref-${pair%%:*}"
                v_disp="ref-${pair##*:}"
                ppl="${ppl_results[$ref_key]}"
                sweep_sd="${ppl_sweep_sd_results[$ref_key]}"
                chunk_sd="${ppl_chunk_sd_results[$ref_key]}"
                elapsed="${time_results[$ref_key]}"
                elapsed_sd="${time_sd_results[$ref_key]}"
                is_m="no"
                [ "${pair%%:*}" != "${pair##*:}" ] && is_m="yes"
                ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
                ppl_vs_f16_sd=$(csv_regression_sd "$sweep_sd" "$baseline_ppl")
                time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
                time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
                csv_append "$k_disp" "$v_disp" "$is_m" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$sweep_sd" "$chunk_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg"
            done
        fi
    fi

    # Clean up per-config associative arrays
    unset ppl_results ppl_sweep_sd_results ppl_chunk_sd_results time_results time_sd_results
    unset ppl_results_a ppl_sweep_sd_results_a ppl_chunk_sd_results_a time_results_a time_sd_results_a

done  # end config loop

echo ""
echo "GPU device: $GPU_DEVICE"
if [ "$num_failed" -eq 0 ]; then
    echo "All checks passed."
else
    echo "$num_failed check(s) failed."
fi
if [ -n "$CSV_FINAL" ]; then
    cp "$CSV_FILE" "$CSV_FINAL"
    rm -f "$CSV_FILE"
    echo ""
    echo "=========================================="
    echo " Output files"
    echo "=========================================="
    echo " CSV: $(readlink -f "$CSV_FINAL") (${#CSV_ROWS[@]} rows)"
    echo " Log: $(readlink -f "$LOG_FILE")"
    echo "=========================================="
fi
