#!/usr/bin/env bash
#
# Benchmark KV cache quantization throughput (prefill pp & decode tg t/s).
# Auto-detects coopmat1/coopmat2 GPU support and compares cooperative matrix
# flash attention vs scalar fallback for TBQ/PQ quantizations.
#
# Usage:
#   tests/test-kv-cache-quantization-perf.sh [options] [build_dir]
#
# Options:
#   -c <tiny|small|mid|large>     Size config preset (repeatable, default: small)
#   -r <n>                       Override preset repetitions (applies to all configs)
#   -m <preset>                  Model preset (see -h for list, default: mistral-q4ks)
#   --all                        Run all model presets sequentially
#   --csv <file>                 Write results to specific CSV file (auto-generated by default)
#   --ref-impl <path>            Reference turboquant repo (default: ../llama-cpp-turboquant, e.g. TheTom)
#   --ref-ks <type> [<type>...]  K cache types from ref impl (default: turbo3 turbo4)
#   --ref-vs <type> [<type>...]  V cache types from ref impl (default: turbo3 turbo4)
#
# Config presets (pp / tg / reps):
#   tiny   — pp 128,  tg 32,  reps 1  (very quick smoke test)
#   small  — pp 128,  tg 32,  reps 3  (quick with stdev)
#   mid    — pp 512,  tg 128, reps 3  (balanced with stdev)
#   large  — pp 2048, tg 512, reps 5  (full stress test with stdev)
#
# Without -c, env vars PROMPT_LEN, GEN_LEN, REPS are used directly.
#
# Environment variables:
#   MODEL_DIR    — directory for model files (default: models)
#   MODEL_NAME   — GGUF filename
#   MODEL_URL    — download URL
#   PROMPT_LEN   — prompt length when no -c given (default: 512)
#   GEN_LEN      — gen length when no -c given (default: 128)
#   REPS         — repetitions when no -c given (default: 3)
#   CSV          — set to 0 to disable auto CSV output (default: 1)
#   SKIP_COOPMAT_COMPARE — set to 1 to skip the coopmat-disabled runs
#   FORCE_COOPMAT — override autodetect: "cm1", "cm2", "both", or "none"
#
# Examples:
#   tests/test-kv-cache-quantization-perf.sh -c small -c mid --csv results.csv
#   tests/test-kv-cache-quantization-perf.sh -c large -r 10 --csv results.csv build
#   PROMPT_LEN=256 GEN_LEN=64 REPS=5 tests/test-kv-cache-quantization-perf.sh build
#
set -euo pipefail

# --- Model presets ---

declare -A MODEL_PRESETS_NAME MODEL_PRESETS_URL
MODEL_PRESETS_NAME[mistral-q4ks]="Mistral-7B-Instruct-v0.3-Q4_K_S.gguf"
MODEL_PRESETS_URL[mistral-q4ks]="https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf"
MODEL_PRESETS_NAME[mistral-q4km]="Mistral-7B-Instruct-v0.3-Q4_K_M.gguf"
MODEL_PRESETS_URL[mistral-q4km]="https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf"
MODEL_PRESETS_NAME[mistral-f16]="Mistral-7B-Instruct-v0.3.fp16.gguf"
MODEL_PRESETS_URL[mistral-f16]="https://huggingface.co/MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3.fp16.gguf"
MODEL_PRESETS_NAME[llama-q4km]="Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_URL[llama-q4km]="https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_NAME[llama-f16]="Llama-3.1-8B-Instruct-f16.gguf"
MODEL_PRESETS_URL[llama-f16]="https://huggingface.co/second-state/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Llama-3.1-8B-Instruct-f16.gguf"
MODEL_PRESETS_NAME[qwen-q4km]="Qwen2.5-14B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_URL[qwen-q4km]="https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf"
MODEL_PRESETS_NAME[qwen05-q8]="Qwen2.5-0.5B-Instruct-Q8_0.gguf"
MODEL_PRESETS_URL[qwen05-q8]="https://huggingface.co/bartowski/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/Qwen2.5-0.5B-Instruct-Q8_0.gguf"

ALL_MODEL_PRESETS=("mistral-q4km" "llama-q4km" "qwen-q4km" "qwen05-q8")

# --- Parse arguments ---

CONFIGS=()
REPS_ARG=""
CSV_FILE=""
BUILD_DIR=""
MODEL_PRESET=""
RUN_ALL=false
REF_IMPL=""
REF_KS=()
REF_VS=()

while [ $# -gt 0 ]; do
    case "$1" in
        -c)
            shift
            CONFIGS+=("$1")
            shift
            ;;
        -r)
            shift
            REPS_ARG="$1"
            shift
            ;;
        --csv)
            shift
            CSV_FILE="$1"
            shift
            ;;
        -m)
            shift
            MODEL_PRESET="$1"
            shift
            ;;
        --all)
            RUN_ALL=true
            shift
            ;;
        --ref-impl)
            shift
            REF_IMPL="$1"
            shift
            ;;
        --ref-ks)
            shift
            while [ $# -gt 0 ] && [[ "$1" != -* ]]; do
                REF_KS+=("$1")
                shift
            done
            ;;
        --ref-vs)
            shift
            while [ $# -gt 0 ] && [[ "$1" != -* ]]; do
                REF_VS+=("$1")
                shift
            done
            ;;
        -h|--help)
            head -39 "$0" | tail -38
            echo ""
            echo "Model presets (-m):"
            for k in "${ALL_MODEL_PRESETS[@]}"; do
                echo "  $k  →  ${MODEL_PRESETS_NAME[$k]}"
            done
            echo "  --all runs all presets sequentially"
            echo ""
            echo "Reference implementation (--ref-impl):"
            echo "  --ref-impl <path>  Path to reference repo (default: ../llama-cpp-turboquant)"
            echo "  --ref-ks <types>   K cache types from ref impl (default: turbo3 turbo4)"
            echo "  --ref-vs <types>   V cache types from ref impl (default: turbo3 turbo4)"
            echo "  Rows appear as ref-turbo3, ref-turbo4, etc."
            exit 0
            ;;
        *)
            BUILD_DIR="$1"
            shift
            ;;
    esac
done

# --- Handle --all: re-exec for each model preset ---

if [ "$RUN_ALL" = true ]; then
    SELF="$0"
    PASS_ARGS=()
    for arg_c in "${CONFIGS[@]}"; do PASS_ARGS+=("-c" "$arg_c"); done
    [ -n "$REPS_ARG" ] && PASS_ARGS+=("-r" "$REPS_ARG")
    if [ -n "$REF_IMPL" ]; then
        PASS_ARGS+=("--ref-impl" "$REF_IMPL")
    fi
    if [ ${#REF_KS[@]} -gt 0 ]; then
        PASS_ARGS+=("--ref-ks" "${REF_KS[@]}")
    fi
    if [ ${#REF_VS[@]} -gt 0 ]; then
        PASS_ARGS+=("--ref-vs" "${REF_VS[@]}")
    fi
    [ -n "${BUILD_DIR:-}" ] && PASS_ARGS+=("$BUILD_DIR")

    echo "=========================================="
    echo " Running all model presets sequentially"
    echo "=========================================="
    echo ""
    for preset in "${ALL_MODEL_PRESETS[@]}"; do
        echo ">>> Starting: $preset (${MODEL_PRESETS_NAME[$preset]})"
        echo ""
        "$SELF" -m "$preset" "${PASS_ARGS[@]}" || echo ">>> FAILED: $preset"
        echo ""
        echo ">>> Finished: $preset"
        echo ""
    done
    echo "=========================================="
    echo " All model presets complete. Log files:"
    echo "=========================================="
    ls -1t kv-perf_*.txt 2>/dev/null | head -20
    exit 0
fi

BUILD_DIR="${BUILD_DIR:-build}"
BENCH="$BUILD_DIR/bin/llama-bench"

# --- Reference implementation setup ---

REF_BENCH=""
REF_CONFIGS=()
REF_GIT_INFO=""
REF_GIT_BRANCH=""
REF_GIT_DIRTY=""
REF_GIT_ORIGIN=""

REF_IMPL="${REF_IMPL:-../llama-cpp-turboquant}"
[ ${#REF_KS[@]} -eq 0 ] && REF_KS=("turbo3" "turbo4")
[ ${#REF_VS[@]} -eq 0 ] && REF_VS=("turbo3" "turbo4")

if [ ! -d "$REF_IMPL" ]; then
    echo "Note: reference implementation not found at $REF_IMPL — skipping ref rows."
elif [ ! -f "$REF_IMPL/build/bin/llama-bench" ]; then
    echo "Note: reference bench binary not found at $REF_IMPL/build/bin/llama-bench — skipping ref rows."
else
    REF_BENCH="$REF_IMPL/build/bin/llama-bench"

    for rk in "${REF_KS[@]}"; do
        for rv in "${REF_VS[@]}"; do
            REF_CONFIGS+=("${rk}:${rv}")
        done
    done

    if command -v git &> /dev/null && git -C "$REF_IMPL" rev-parse --git-dir &> /dev/null; then
        REF_GIT_INFO=$(git -C "$REF_IMPL" log --oneline -3 2>/dev/null || true)
        REF_GIT_BRANCH=$(git -C "$REF_IMPL" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
        REF_GIT_DIRTY=$(git -C "$REF_IMPL" diff --quiet 2>/dev/null && echo "" || echo " (dirty)")
        REF_GIT_ORIGIN=$(git -C "$REF_IMPL" remote get-url origin 2>/dev/null || echo "")
    fi

fi

MODEL_DIR="${MODEL_DIR:-models}"

if [ -n "$MODEL_PRESET" ]; then
    if [ -z "${MODEL_PRESETS_NAME[$MODEL_PRESET]:-}" ]; then
        echo "Error: unknown model preset '$MODEL_PRESET'"
        echo "Available: ${ALL_MODEL_PRESETS[*]}"
        exit 1
    fi
    MODEL_NAME="${MODEL_PRESETS_NAME[$MODEL_PRESET]}"
    MODEL_URL="${MODEL_PRESETS_URL[$MODEL_PRESET]}"
else
    MODEL_NAME="${MODEL_NAME:-Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
    MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
fi
MODEL_PATH="$MODEL_DIR/$MODEL_NAME"

SKIP_COOPMAT_COMPARE="${SKIP_COOPMAT_COMPARE:-0}"
FORCE_COOPMAT="${FORCE_COOPMAT:-}"

# When no -c is given, default to small
if [ ${#CONFIGS[@]} -eq 0 ]; then
    CONFIGS=("small")
fi


# --- Config presets ---

config_prompt_len() {
    case "$1" in
        tiny)  echo 128  ;;
        small) echo 128  ;;
        mid)   echo 512  ;;
        large) echo 2048 ;;
        env)   echo "${PROMPT_LEN:-512}" ;;
        *) echo "Error: unknown config '$1' (expected tiny, small, mid, large)" >&2; exit 1 ;;
    esac
}

config_gen_len() {
    case "$1" in
        tiny)  echo 32  ;;
        small) echo 32  ;;
        mid)   echo 128 ;;
        large) echo 512 ;;
        env)   echo "${GEN_LEN:-128}" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

config_reps() {
    case "$1" in
        tiny)  echo 1 ;;
        small) echo 3 ;;
        mid)   echo 3 ;;
        large) echo 5 ;;
        env)   echo "${REPS:-3}" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

# --- Validate ---

if [ ! -f "$BENCH" ]; then
    echo "Error: $BENCH not found. Build the project first."
    echo "  cmake -B $BUILD_DIR && cmake --build $BUILD_DIR -j\$(nproc)"
    exit 1
fi

# --- Single-GPU execution mode ---
SPLIT_MODE="${SPLIT_MODE:-none}"
SPLIT_ARGS=()
if [ -n "$SPLIT_MODE" ]; then
    SPLIT_ARGS=(--split-mode "$SPLIT_MODE")
fi

mkdir -p "$MODEL_DIR"

if [ ! -f "$MODEL_PATH" ] || [ "$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)" -lt 1000000 ]; then
    [ -f "$MODEL_PATH" ] && rm -f "$MODEL_PATH"
    echo "Downloading model: $MODEL_NAME ..."
    if command -v curl &> /dev/null; then
        curl -L --fail -C - -o "$MODEL_PATH" "$MODEL_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$MODEL_PATH" "$MODEL_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi
    FILE_SIZE=$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [ "$FILE_SIZE" -lt 1000000 ]; then
        echo "Error: downloaded file is only $FILE_SIZE bytes."
        rm -f "$MODEL_PATH"
        exit 1
    fi
    echo "Model downloaded to $MODEL_PATH ($((FILE_SIZE / 1048576)) MB)"
else
    echo "Model already exists: $MODEL_PATH"
fi

# --- GPU device detection ---

detect_gpu_device() {
    local gpu_info=""

    if [ -f "$BENCH" ]; then
        gpu_info=$("$BENCH" --list-devices 2>&1 | grep -E '^\s+(Vulkan|CUDA|Metal|SYCL|ROCm)' | head -1 | sed 's/^[[:space:]]*//' || true)
    fi

    if [ -z "$gpu_info" ]; then
        if command -v nvidia-smi &> /dev/null; then
            gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
        elif command -v vulkaninfo &> /dev/null; then
            gpu_info=$(vulkaninfo 2>/dev/null | grep "deviceName" | head -1 | sed 's/.*= //' || true)
        fi
    fi

    echo "${gpu_info:-unknown}"
}

GPU_DEVICE=$(detect_gpu_device)

# Auto-generate CSV filename unless explicitly provided or disabled (CSV=0)
CSV_FINAL=""
if [ -z "$CSV_FILE" ] && [ "${CSV:-1}" != "0" ]; then
    sanitize() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g; s/__*/_/g; s/^_//; s/_$//'; }
    GPU_SHORT=$(echo "$GPU_DEVICE" | sed 's/^[A-Za-z]*[0-9]*: //; s/ ([0-9].*//')
    GPU_TAG=$(sanitize "$GPU_SHORT")
    MODEL_TAG=$(sanitize "${MODEL_NAME%.gguf}")
    CFG_TAG=$(printf '%s-' "${CONFIGS[@]}" | sed 's/-$//')
    CSV_FILE="kv-perf_${GPU_TAG}_${MODEL_TAG}_${CFG_TAG}_$(date +%Y%m%d_%H%M%S).csv"
fi
if [ -n "$CSV_FILE" ]; then
    CSV_FINAL="$CSV_FILE"
    CSV_FILE=$(mktemp /tmp/kv-perf-XXXXXX.csv)
fi

# --- Log file setup (same name as CSV, .txt extension) ---

LOG_FILE=""
if [ -n "$CSV_FINAL" ]; then
    LOG_FILE="${CSV_FINAL%.csv}.txt"
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

# --- Detect coopmat support ---

detect_coopmat() {
    if [ -n "$FORCE_COOPMAT" ]; then
        echo "$FORCE_COOPMAT"
        return
    fi

    if ! command -v vulkaninfo &> /dev/null; then
        echo "Warning: vulkaninfo not found, cannot autodetect coopmat. Assuming none." >&2
        echo "none"
        return
    fi

    local vk_extensions
    vk_extensions=$(vulkaninfo 2>/dev/null || true)

    if [ -z "$vk_extensions" ]; then
        echo "Warning: vulkaninfo produced no output, assuming no coopmat support." >&2
        echo "none"
        return
    fi

    local has_cm1=0 has_cm2=0
    grep -q "VK_KHR_cooperative_matrix" <<< "$vk_extensions" && has_cm1=1
    grep -q "VK_NV_cooperative_matrix2" <<< "$vk_extensions" && has_cm2=1

    if [ "$has_cm1" = "1" ] && [ "$has_cm2" = "1" ]; then
        echo "both"
    elif [ "$has_cm2" = "1" ]; then
        echo "cm2"
    elif [ "$has_cm1" = "1" ]; then
        echo "cm1"
    else
        echo "none"
    fi
}

COOPMAT_LEVEL=$(detect_coopmat)

COOPMAT_LEVELS=()
case "$COOPMAT_LEVEL" in
    both)
        COOPMAT_LEVELS=("cm1" "cm2")
        ;;
    cm2)
        COOPMAT_LEVELS=("cm2")
        ;;
    cm1)
        COOPMAT_LEVELS=("cm1")
        ;;
    none)
        COOPMAT_LEVELS=()
        SKIP_COOPMAT_COMPARE=1
        ;;
    *)
        echo "Error: unknown FORCE_COOPMAT value '$COOPMAT_LEVEL' (expected cm1, cm2, both, or none)"
        exit 1
        ;;
esac

coopmat_label_for() {
    case "$1" in
        cm1) echo "coopmat1" ;;
        cm2) echo "coopmat2" ;;
        *)   echo "scalar"  ;;
    esac
}

coopmat_env_for() {
    case "$1" in
        cm1) echo "GGML_VK_DISABLE_COOPMAT2=1" ;;
        cm2) echo "" ;;
        *)   echo "GGML_VK_DISABLE_COOPMAT=1 GGML_VK_DISABLE_COOPMAT2=1" ;;
    esac
}

SCALAR_DISABLE_ENV="GGML_VK_DISABLE_COOPMAT=1 GGML_VK_DISABLE_COOPMAT2=1"

if [ ${#COOPMAT_LEVELS[@]} -gt 0 ]; then
    COOPMAT_DISPLAY=$(printf '%s+' "${COOPMAT_LEVELS[@]}")
    COOPMAT_DISPLAY="${COOPMAT_DISPLAY%+}"
else
    COOPMAT_DISPLAY="none"
fi

# --- Unified K:V config list ---

ALL_CONFIGS=(
    "f16:f16"
    "q8_0:q8_0"
    "q4_0:q4_0"
    "pq3_0:pq3_0"
    "pq4_0:pq4_0"
    "tbq4_0:pq4_0"
    "tbq3_0:pq3_0"
    "tbq3_0:q4_0"
    "tbq4_0:q4_0"
    "tbq3_0:q8_0"
    "tbq4_0:f16"
)

# --- KV cache size probing (measured, not theoretical) ---

declare -A KV_SIZE_MIB

probe_kv_sizes() {
    echo "--- Probing KV cache sizes (measured) ---"
    echo ""
    for pair in "${ALL_CONFIGS[@]}"; do
        k_type="${pair%%:*}"
        v_type="${pair##*:}"
        local output
        output=$("$BENCH" -v \
            "${SPLIT_ARGS[@]}" \
            -m "$MODEL_PATH" \
            --cache-type-k "$k_type" \
            --cache-type-v "$v_type" \
            -fa 1 -p 1 -n 0 -r 1 \
            2>&1) || {
            echo "  WARNING: could not probe KV size for K=$k_type V=$v_type" >&2
            continue
        }
        local total_mib
        total_mib=$(echo "$output" | grep "llama_kv_cache: size" | head -1 | sed 's/.*size = *//; s/ MiB.*//')
        if [ -n "$total_mib" ]; then
            KV_SIZE_MIB["$pair"]="$total_mib"
            echo "  K=$k_type V=$v_type: $total_mib MiB"
        else
            echo "  WARNING: could not parse KV size for K=$k_type V=$v_type" >&2
        fi
    done
    echo ""

    if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
        echo "  --- ref impl  ---"
        for pair in "${REF_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            ref_key="ref-${k_type}:ref-${v_type}"
            local output
            output=$("$REF_BENCH" -v \
                "${SPLIT_ARGS[@]}" \
                -m "$MODEL_PATH" \
                --cache-type-k "$k_type" \
                --cache-type-v "$v_type" \
                -fa 1 -p 1 -n 0 -r 1 \
                2>&1) || {
                echo "  WARNING: could not probe KV size for ref K=$k_type V=$v_type" >&2
                continue
            }
            local total_mib
            total_mib=$(echo "$output" | grep "llama_kv_cache: size" | head -1 | sed 's/.*size = *//; s/ MiB.*//')
            if [ -n "$total_mib" ]; then
                KV_SIZE_MIB["$ref_key"]="$total_mib"
                echo "  K=ref-$k_type V=ref-$v_type: $total_mib MiB"
            else
                echo "  WARNING: could not parse KV size for ref K=$k_type V=$v_type" >&2
            fi
        done
        echo ""
    fi

    local f16_size="${KV_SIZE_MIB[f16:f16]:-}"
    if [ -n "$f16_size" ]; then
        echo "  f16 baseline: $f16_size MiB"
        for pair in "${ALL_CONFIGS[@]}"; do
            [ "$pair" = "f16:f16" ] && continue
            local sz="${KV_SIZE_MIB[$pair]:-}"
            if [ -n "$sz" ]; then
                local ratio
                ratio=$(echo "$f16_size $sz" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                echo "  K=${pair%%:*} V=${pair##*:}: ${sz} MiB (${ratio}x compression)"
            fi
        done
        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                local sz="${KV_SIZE_MIB[$ref_key]:-}"
                if [ -n "$sz" ]; then
                    local ratio
                    ratio=$(echo "$f16_size $sz" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    echo "  K=ref-${pair%%:*} V=ref-${pair##*:}: ${sz} MiB (${ratio}x compression)"
                fi
            done
        fi
    fi
    echo ""
}

probe_kv_sizes

get_compression() {
    local pair="$1"
    local f16_size="${KV_SIZE_MIB[f16:f16]:-}"
    local sz="${KV_SIZE_MIB[$pair]:-}"
    if [ -n "$f16_size" ] && [ -n "$sz" ]; then
        echo "$f16_size $sz" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}'
    else
        echo "n/a"
    fi
}

# --- Extraction helpers (avg ± stdev) ---

extract_pp() {
    echo "$1" | grep -E '^\|' | grep -E '\bpp[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[1]}' | tail -1
}

extract_pp_stdev() {
    echo "$1" | grep -E '^\|' | grep -E '\bpp[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[2]}' | tail -1
}

extract_tg() {
    echo "$1" | grep -E '^\|' | grep -E '\btg[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[1]}' | tail -1
}

extract_tg_stdev() {
    echo "$1" | grep -E '^\|' | grep -E '\btg[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[2]}' | tail -1
}

run_bench() {
    local k_type="$1"
    local v_type="$2"
    local env_prefix="$3"
    local label="$4"
    local prompt_len="$5"
    local gen_len="$6"
    local reps="$7"
    local bench_bin="${8:-$BENCH}"

    local output
    output=$(env $env_prefix "$bench_bin" \
        "${SPLIT_ARGS[@]}" \
        -m "$MODEL_PATH" \
        --cache-type-k "$k_type" \
        --cache-type-v "$v_type" \
        -fa 1 \
        -p "$prompt_len" \
        -n "$gen_len" \
        -r "$reps" \
        2>&1) || {
        echo "  FAILED: $label (K=$k_type V=$v_type)" >&2
        echo "$output" | tail -5 >&2
        return 1
    }

    if echo "$output" | grep -q "error:"; then
        echo "  FAILED: $label (K=$k_type V=$v_type) — $(echo "$output" | grep 'error:' | head -1)" >&2
        return 1
    fi

    local pp pp_sd tg tg_sd
    pp=$(extract_pp "$output")
    pp_sd=$(extract_pp_stdev "$output")
    tg=$(extract_tg "$output")
    tg_sd=$(extract_tg_stdev "$output")

    if [ -z "$pp" ] || [ -z "$tg" ]; then
        echo "  FAILED: $label — could not parse t/s from output" >&2
        return 1
    fi

    pp_sd="${pp_sd:-0.00}"
    tg_sd="${tg_sd:-0.00}"

    echo "$pp $pp_sd $tg $tg_sd"
}

# --- CSV setup ---

CSV_ROWS=()

csv_init() {
    if [ -n "$CSV_FILE" ]; then
        echo "gpu_device,model,config,coopmat_mode,cache_k,cache_v,mixed,kv_size_mib,compression_vs_f16,prompt_len,gen_len,reps,pp_avg,pp_stdev,tg_avg,tg_stdev,pp_vs_f16_x,tg_vs_f16_x,pp_speedup_vs_scalar,tg_speedup_vs_scalar" > "$CSV_FILE"
    fi
}

csv_append() {
    local cm_mode="$1" k_type="$2" v_type="$3" is_mixed="$4" prompt_len="$5" gen_len="$6"
    local pp_avg="$7" pp_sd="$8" tg_avg="$9" tg_sd="${10}" config_name="${11}" reps="${12}"
    local pp_vs_f16="${13}" tg_vs_f16="${14}" pp_vs_scalar="${15}" tg_vs_scalar="${16}"
    local kv_mib="${KV_SIZE_MIB[$k_type:$v_type]:-}"
    local compr=""
    local f16_sz="${KV_SIZE_MIB[f16:f16]:-}"
    if [ -n "$kv_mib" ] && [ -n "$f16_sz" ]; then
        compr=$(echo "$f16_sz $kv_mib" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
    fi
    local row="\"$GPU_DEVICE\",\"$MODEL_NAME\",\"$config_name\",\"$cm_mode\",\"$k_type\",\"$v_type\",\"$is_mixed\",$kv_mib,$compr,$prompt_len,$gen_len,$reps,$pp_avg,$pp_sd,$tg_avg,$tg_sd,$pp_vs_f16,$tg_vs_f16,$pp_vs_scalar,$tg_vs_scalar"
    CSV_ROWS+=("$row")
    if [ -n "$CSV_FILE" ]; then
        echo "$row" >> "$CSV_FILE"
    fi
}

csv_init

# --- Git info ---

GIT_INFO=""
if command -v git &> /dev/null && git rev-parse --git-dir &> /dev/null; then
    GIT_INFO=$(git log --oneline -3 2>/dev/null || true)
    GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    GIT_DIRTY=$(git diff --quiet 2>/dev/null && echo "" || echo " (dirty)")
    GIT_ORIGIN=$(git remote get-url origin 2>/dev/null || echo "")
fi

# --- Print header ---

echo ""
echo "=========================================="
echo " KV Cache Quantization Performance Test"
echo "=========================================="
if [ -n "$GIT_INFO" ]; then
    [ -n "$GIT_ORIGIN" ] && echo " Origin:      $GIT_ORIGIN"
    echo " Branch:      ${GIT_BRANCH}${GIT_DIRTY}"
    echo "$GIT_INFO" | while IFS= read -r line; do
        echo "              $line"
    done
fi
echo " GPU:         $GPU_DEVICE"
echo " Split mode:  ${SPLIT_MODE:-default}"
echo " Model:       $MODEL_NAME"
echo " Configs:     ${CONFIGS[*]}"
for cfg_info in "${CONFIGS[@]}"; do
    local_pp=$(config_prompt_len "$cfg_info")
    local_tg=$(config_gen_len "$cfg_info")
    local_reps=$(config_reps "$cfg_info")
    [ -n "$REPS_ARG" ] && local_reps="$REPS_ARG"
    echo "   $cfg_info: pp=$local_pp tg=$local_tg reps=$local_reps"
done
if [ -n "$REPS_ARG" ]; then
    echo " Reps override: $REPS_ARG"
fi
echo " GPU coopmat: $COOPMAT_LEVEL ($COOPMAT_DISPLAY)"
if [ "$SKIP_COOPMAT_COMPARE" = "1" ]; then
    echo " Compare:     disabled"
else
    for lvl in "${COOPMAT_LEVELS[@]}"; do
        echo " Compare:     $(coopmat_label_for "$lvl") vs scalar"
    done
fi
if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
    echo " ──────────────────────────────────────"
    echo " Ref impl:    $(readlink -f "$REF_IMPL")"
    echo " Ref bin:     $REF_BENCH"
    if [ -n "$REF_GIT_INFO" ]; then
        [ -n "$REF_GIT_ORIGIN" ] && echo " Ref origin:  $REF_GIT_ORIGIN"
        echo " Ref branch:  ${REF_GIT_BRANCH}${REF_GIT_DIRTY}"
        echo "$REF_GIT_INFO" | while IFS= read -r line; do
            echo "              $line"
        done
    fi
    echo " Ref K types: ${REF_KS[*]}"
    echo " Ref V types: ${REF_VS[*]}"
    echo " Ref configs: ${REF_CONFIGS[*]}"
fi
if [ -n "$CSV_FINAL" ]; then
    echo " CSV output:  $CSV_FINAL"
    echo " Log output:  $LOG_FILE"
fi
echo "=========================================="
echo ""

# --- Main benchmark loop over configs ---

for cfg in "${CONFIGS[@]}"; do
    PROMPT_LEN_CFG=$(config_prompt_len "$cfg")
    GEN_LEN_CFG=$(config_gen_len "$cfg")
    REPS_CFG=$(config_reps "$cfg")
    [ -n "$REPS_ARG" ] && REPS_CFG="$REPS_ARG"

    HAS_STDEV=$(( REPS_CFG > 1 ))

    echo ""
    echo "############################################"
    echo " Config: $cfg  (pp=$PROMPT_LEN_CFG, tg=$GEN_LEN_CFG, reps=$REPS_CFG)"
    echo "############################################"
    echo ""

    # --- Count total jobs for ETA ---

    total_jobs=0
    n_configs=${#ALL_CONFIGS[@]}
    # coopmat levels
    total_jobs=$(( total_jobs + ${#COOPMAT_LEVELS[@]} * n_configs ))
    # scalar fallback (either no coopmat, or coopmat-compare)
    if [ ${#COOPMAT_LEVELS[@]} -eq 0 ]; then
        total_jobs=$(( total_jobs + n_configs ))
    fi
    if [ "$SKIP_COOPMAT_COMPARE" != "1" ] && [ ${#COOPMAT_LEVELS[@]} -gt 0 ]; then
        total_jobs=$(( total_jobs + n_configs ))
    fi
    # ref impl: scalar + each coopmat level
    if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
        ref_per_pair=$(( 1 + ${#COOPMAT_LEVELS[@]} ))
        total_jobs=$(( total_jobs + ${#REF_CONFIGS[@]} * ref_per_pair ))
    fi
    completed_jobs=0
    bench_start_time=$(date +%s)

    fmt_eta() {
        local done="$1" total="$2" start="$3"
        if [ "$done" -eq 0 ]; then echo "estimating..."; return; fi
        local now elapsed avg remaining
        now=$(date +%s)
        elapsed=$((now - start))
        avg=$((elapsed / done))
        remaining=$(( avg * (total - done) ))
        if [ "$remaining" -ge 3600 ]; then
            printf "%dh%02dm" $((remaining/3600)) $(( (remaining%3600)/60 ))
        elif [ "$remaining" -ge 60 ]; then
            printf "%dm%02ds" $((remaining/60)) $((remaining%60))
        else
            printf "%ds" "$remaining"
        fi
    }

    # --- Run all configs ---

    declare -A pp_scalar tg_scalar ppsd_scalar tgsd_scalar

    for lvl in "${COOPMAT_LEVELS[@]}"; do
        declare -A "pp_${lvl}" "tg_${lvl}" "ppsd_${lvl}" "tgsd_${lvl}"
        local_label=$(coopmat_label_for "$lvl")
        local_env=$(coopmat_env_for "$lvl")

        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
            echo "[$((completed_jobs+1))/$total_jobs, ETA $eta] Running: K=$k_type V=$v_type ($local_label, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "$local_env" "$local_label" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || { completed_jobs=$((completed_jobs + 1)); continue; }
            eval "pp_${lvl}[\"$pair\"]=$(echo "$result" | awk '{print $1}')"
            eval "ppsd_${lvl}[\"$pair\"]=$(echo "$result" | awk '{print $2}')"
            eval "tg_${lvl}[\"$pair\"]=$(echo "$result" | awk '{print $3}')"
            eval "tgsd_${lvl}[\"$pair\"]=$(echo "$result" | awk '{print $4}')"
            completed_jobs=$((completed_jobs + 1))
            eval "echo \"  pp=\${pp_${lvl}[$pair]}±\${ppsd_${lvl}[$pair]} t/s  tg=\${tg_${lvl}[$pair]}±\${tgsd_${lvl}[$pair]} t/s\""
        done
        echo ""
    done

    if [ ${#COOPMAT_LEVELS[@]} -eq 0 ]; then
        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
            echo "[$((completed_jobs+1))/$total_jobs, ETA $eta] Running: K=$k_type V=$v_type (scalar, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "" "scalar" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || { completed_jobs=$((completed_jobs + 1)); continue; }
            pp_scalar["$pair"]=$(echo "$result" | awk '{print $1}')
            ppsd_scalar["$pair"]=$(echo "$result" | awk '{print $2}')
            tg_scalar["$pair"]=$(echo "$result" | awk '{print $3}')
            tgsd_scalar["$pair"]=$(echo "$result" | awk '{print $4}')
            completed_jobs=$((completed_jobs + 1))
            echo "  pp=${pp_scalar[$pair]}±${ppsd_scalar[$pair]} t/s  tg=${tg_scalar[$pair]}±${tgsd_scalar[$pair]} t/s"
        done
        echo ""
    fi

    if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
            echo "[$((completed_jobs+1))/$total_jobs, ETA $eta] Running: K=$k_type V=$v_type (scalar, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "$SCALAR_DISABLE_ENV" "scalar" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || { completed_jobs=$((completed_jobs + 1)); continue; }
            pp_scalar["$pair"]=$(echo "$result" | awk '{print $1}')
            ppsd_scalar["$pair"]=$(echo "$result" | awk '{print $2}')
            tg_scalar["$pair"]=$(echo "$result" | awk '{print $3}')
            tgsd_scalar["$pair"]=$(echo "$result" | awk '{print $4}')
            completed_jobs=$((completed_jobs + 1))
            echo "  pp=${pp_scalar[$pair]}±${ppsd_scalar[$pair]} t/s  tg=${tg_scalar[$pair]}±${tgsd_scalar[$pair]} t/s"
        done
    fi

    # --- Run reference implementation configs ---

    if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
        echo ""
        for pair in "${REF_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            ref_key="ref-${k_type}:ref-${v_type}"
            eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
            echo "[$((completed_jobs+1))/$total_jobs, ETA $eta] Running: K=ref-$k_type V=ref-$v_type (ref impl, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "" "ref" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG" "$REF_BENCH") || { completed_jobs=$((completed_jobs + 1)); continue; }
            pp_scalar["$ref_key"]=$(echo "$result" | awk '{print $1}')
            ppsd_scalar["$ref_key"]=$(echo "$result" | awk '{print $2}')
            tg_scalar["$ref_key"]=$(echo "$result" | awk '{print $3}')
            tgsd_scalar["$ref_key"]=$(echo "$result" | awk '{print $4}')
            completed_jobs=$((completed_jobs + 1))
            echo "  pp=${pp_scalar[$ref_key]}±${ppsd_scalar[$ref_key]} t/s  tg=${tg_scalar[$ref_key]}±${tgsd_scalar[$ref_key]} t/s"

            if [ ${#COOPMAT_LEVELS[@]} -gt 0 ]; then
                for lvl in "${COOPMAT_LEVELS[@]}"; do
                    local_label=$(coopmat_label_for "$lvl")
                    local_env=$(coopmat_env_for "$lvl")
                    eta=$(fmt_eta "$completed_jobs" "$total_jobs" "$bench_start_time")
                    echo "[$((completed_jobs+1))/$total_jobs, ETA $eta] Running: K=ref-$k_type V=ref-$v_type ($local_label ref, $cfg) ..."
                    result=$(run_bench "$k_type" "$v_type" "$local_env" "$local_label" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG" "$REF_BENCH") || { completed_jobs=$((completed_jobs + 1)); continue; }
                    eval "pp_${lvl}[\"$ref_key\"]=$(echo "$result" | awk '{print $1}')"
                    eval "ppsd_${lvl}[\"$ref_key\"]=$(echo "$result" | awk '{print $2}')"
                    eval "tg_${lvl}[\"$ref_key\"]=$(echo "$result" | awk '{print $3}')"
                    eval "tgsd_${lvl}[\"$ref_key\"]=$(echo "$result" | awk '{print $4}')"
                    completed_jobs=$((completed_jobs + 1))
                    eval "echo \"  pp=\${pp_${lvl}[$ref_key]}±\${ppsd_${lvl}[$ref_key]} t/s  tg=\${tg_${lvl}[$ref_key]}±\${tgsd_${lvl}[$ref_key]} t/s\""
                done
            fi
        done
        echo ""
    fi

    # --- Unified summary table ---

    print_table() {
        local lvl="$1"
        local cm_tag
        cm_tag=$(coopmat_label_for "$lvl")

        echo ""
        echo "=========================================="
        echo " Results [$cfg]: $cm_tag vs scalar (t/s)"
        echo "=========================================="

        printf "  %-10s %-10s %7s %14s %14s %10s %10s %14s %14s %10s %10s\n" \
            "K type" "V type" "compr" "pp($cm_tag)" "pp(scalar)" "pp spdup" "pp vs f16" "tg($cm_tag)" "tg(scalar)" "tg spdup" "tg vs f16"
        printf "  %-10s %-10s %7s %14s %14s %10s %10s %14s %14s %10s %10s\n" \
            "------" "------" "-----" "-------" "----------" "--------" "---------" "------" "---------" "--------" "---------"

        local f16_pp_on="" f16_tg_on="" f16_pp_off="" f16_tg_off=""
        local f16_pp_on_sd="" f16_tg_on_sd="" f16_pp_off_sd="" f16_tg_off_sd=""
        eval "f16_pp_on=\${pp_${lvl}[f16:f16]:-}"
        eval "f16_pp_on_sd=\${ppsd_${lvl}[f16:f16]:-}"
        eval "f16_tg_on=\${tg_${lvl}[f16:f16]:-}"
        eval "f16_tg_on_sd=\${tgsd_${lvl}[f16:f16]:-}"
        f16_pp_off="${pp_scalar[f16:f16]:-}"
        f16_tg_off="${tg_scalar[f16:f16]:-}"

        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            local p_on="" p_on_sd="" p_off="" t_on="" t_on_sd="" t_off="" pp_speedup="n/a" tg_speedup="n/a"
            local pp_vs_f16="n/a" tg_vs_f16="n/a"
            eval "p_on=\${pp_${lvl}[\$pair]:-n/a}"
            eval "p_on_sd=\${ppsd_${lvl}[\$pair]:-}"
            p_off="${pp_scalar[$pair]:-n/a}"
            eval "t_on=\${tg_${lvl}[\$pair]:-n/a}"
            eval "t_on_sd=\${tgsd_${lvl}[\$pair]:-}"
            t_off="${tg_scalar[$pair]:-n/a}"
            if [ "$p_on" != "n/a" ] && [ "$p_off" != "n/a" ]; then
                pp_speedup=$(echo "$p_on $p_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            if [ "$t_on" != "n/a" ] && [ "$t_off" != "n/a" ]; then
                tg_speedup=$(echo "$t_on $t_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            if [ "$pair" = "f16:f16" ]; then
                pp_vs_f16="(baseline)"
                tg_vs_f16="(baseline)"
            else
                [ "$p_on" != "n/a" ] && [ -n "$f16_pp_on" ] && \
                    pp_vs_f16=$(echo "$p_on $f16_pp_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                [ "$t_on" != "n/a" ] && [ -n "$f16_tg_on" ] && \
                    tg_vs_f16=$(echo "$t_on $f16_tg_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            local compr_disp
            if [ "$pair" = "f16:f16" ]; then
                compr_disp="1.00x"
            else
                compr_disp=$(get_compression "$pair")
            fi
            local pp_display="$p_on"
            local tg_display="$t_on"
            [ -n "$p_on_sd" ] && [ "$p_on" != "n/a" ] && pp_display="${p_on}±${p_on_sd}"
            [ -n "$t_on_sd" ] && [ "$t_on" != "n/a" ] && tg_display="${t_on}±${t_on_sd}"
            printf "  %-10s %-10s %7s %14s %14s %10s %10s %14s %14s %10s %10s\n" \
                "$k_type" "$v_type" "$compr_disp" "$pp_display" "$p_off" "$pp_speedup" "$pp_vs_f16" "$tg_display" "$t_off" "$tg_speedup" "$tg_vs_f16"
        done

        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            printf "  %-10s %-10s %7s %14s %14s %10s %10s %14s %14s %10s %10s\n" \
                "---ref---" "---ref---" "-----" "-------" "----------" "--------" "---------" "------" "---------" "--------" "---------"
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                local k_disp="ref-${pair%%:*}" v_disp="ref-${pair##*:}"
                local p_on="" p_on_sd="" p_off="" t_on="" t_on_sd="" t_off=""
                local pp_speedup="n/a" tg_speedup="n/a" pp_vs_f16="n/a" tg_vs_f16="n/a"
                eval "p_on=\${pp_${lvl}[$ref_key]:-n/a}"
                eval "p_on_sd=\${ppsd_${lvl}[$ref_key]:-}"
                eval "t_on=\${tg_${lvl}[$ref_key]:-n/a}"
                eval "t_on_sd=\${tgsd_${lvl}[$ref_key]:-}"
                p_off="${pp_scalar[$ref_key]:-n/a}"
                t_off="${tg_scalar[$ref_key]:-n/a}"
                if [ "$p_on" != "n/a" ] && [ "$p_off" != "n/a" ]; then
                    pp_speedup=$(echo "$p_on $p_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                fi
                if [ "$t_on" != "n/a" ] && [ "$t_off" != "n/a" ]; then
                    tg_speedup=$(echo "$t_on $t_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                fi
                [ "$p_on" != "n/a" ] && [ -n "$f16_pp_on" ] && \
                    pp_vs_f16=$(echo "$p_on $f16_pp_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                [ "$t_on" != "n/a" ] && [ -n "$f16_tg_on" ] && \
                    tg_vs_f16=$(echo "$t_on $f16_tg_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                local compr_disp
                compr_disp=$(get_compression "$ref_key")
                local pp_display="$p_on" tg_display="$t_on"
                [ -n "$p_on_sd" ] && [ "$p_on" != "n/a" ] && pp_display="${p_on}±${p_on_sd}"
                [ -n "$t_on_sd" ] && [ "$t_on" != "n/a" ] && tg_display="${t_on}±${t_on_sd}"
                printf "  %-10s %-10s %7s %14s %14s %10s %10s %14s %14s %10s %10s\n" \
                    "$k_disp" "$v_disp" "$compr_disp" "$pp_display" "$p_off" "$pp_speedup" "$pp_vs_f16" "$tg_display" "$t_off" "$tg_speedup" "$tg_vs_f16"
            done
        fi

        echo "=========================================="
    }

    print_vs_f16_table() {
        local lvl="$1"
        local cm_tag
        cm_tag=$(coopmat_label_for "$lvl")

        local f16_pp_on="" f16_tg_on="" f16_pp_off="" f16_tg_off=""
        local f16_pp_on_sd="" f16_tg_on_sd="" f16_pp_off_sd="" f16_tg_off_sd=""
        eval "f16_pp_on=\${pp_${lvl}[f16:f16]:-}"
        eval "f16_pp_on_sd=\${ppsd_${lvl}[f16:f16]:-}"
        eval "f16_tg_on=\${tg_${lvl}[f16:f16]:-}"
        eval "f16_tg_on_sd=\${tgsd_${lvl}[f16:f16]:-}"
        f16_pp_off="${pp_scalar[f16:f16]:-}"
        f16_pp_off_sd="${ppsd_scalar[f16:f16]:-}"
        f16_tg_off="${tg_scalar[f16:f16]:-}"
        f16_tg_off_sd="${tgsd_scalar[f16:f16]:-}"

        echo ""
        echo "=========================================="
        echo " vs f16 Baseline [$cfg]: $cm_tag + scalar"
        echo "=========================================="

        if [ "$HAS_STDEV" -eq 1 ]; then
            printf "  %-10s %-10s %16s %16s %16s %16s\n" \
                "K type" "V type" "pp($cm_tag)" "pp(scalar)" "tg($cm_tag)" "tg(scalar)"
        else
            printf "  %-10s %-10s %12s %12s %12s %12s\n" \
                "K type" "V type" "pp($cm_tag)" "pp(scalar)" "tg($cm_tag)" "tg(scalar)"
        fi
        printf "  %-10s %-10s %16s %16s %16s %16s\n" \
            "------" "------" "-------" "----------" "------" "---------"

        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            local p_on="" t_on="" p_off="" t_off=""
            local p_on_sd="" t_on_sd="" p_off_sd="" t_off_sd=""
            local pp_vs_f16_on="n/a" tg_vs_f16_on="n/a" pp_vs_f16_off="n/a" tg_vs_f16_off="n/a"
            eval "p_on=\${pp_${lvl}[\$pair]:-}"
            eval "p_on_sd=\${ppsd_${lvl}[\$pair]:-}"
            eval "t_on=\${tg_${lvl}[\$pair]:-}"
            eval "t_on_sd=\${tgsd_${lvl}[\$pair]:-}"
            p_off="${pp_scalar[$pair]:-}"
            p_off_sd="${ppsd_scalar[$pair]:-}"
            t_off="${tg_scalar[$pair]:-}"
            t_off_sd="${tgsd_scalar[$pair]:-}"

            if [ "$pair" = "f16:f16" ]; then
                pp_vs_f16_on="(baseline)"
                tg_vs_f16_on="(baseline)"
                pp_vs_f16_off="(baseline)"
                tg_vs_f16_off="(baseline)"
            else
                if [ -n "$p_on" ] && [ -n "$f16_pp_on" ]; then
                    local ratio_val=$(echo "$p_on $f16_pp_on" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$p_on_sd" ] && [ -n "$f16_pp_on_sd" ]; then
                        local ratio_sd=$(echo "$p_on $p_on_sd $f16_pp_on $f16_pp_on_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        pp_vs_f16_on="${ratio_val}±${ratio_sd}x"
                    else
                        pp_vs_f16_on="${ratio_val}x"
                    fi
                fi
                if [ -n "$t_on" ] && [ -n "$f16_tg_on" ]; then
                    local ratio_val=$(echo "$t_on $f16_tg_on" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$t_on_sd" ] && [ -n "$f16_tg_on_sd" ]; then
                        local ratio_sd=$(echo "$t_on $t_on_sd $f16_tg_on $f16_tg_on_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        tg_vs_f16_on="${ratio_val}±${ratio_sd}x"
                    else
                        tg_vs_f16_on="${ratio_val}x"
                    fi
                fi
                if [ -n "$p_off" ] && [ -n "$f16_pp_off" ]; then
                    local ratio_val=$(echo "$p_off $f16_pp_off" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$p_off_sd" ] && [ -n "$f16_pp_off_sd" ]; then
                        local ratio_sd=$(echo "$p_off $p_off_sd $f16_pp_off $f16_pp_off_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        pp_vs_f16_off="${ratio_val}±${ratio_sd}x"
                    else
                        pp_vs_f16_off="${ratio_val}x"
                    fi
                fi
                if [ -n "$t_off" ] && [ -n "$f16_tg_off" ]; then
                    local ratio_val=$(echo "$t_off $f16_tg_off" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$t_off_sd" ] && [ -n "$f16_tg_off_sd" ]; then
                        local ratio_sd=$(echo "$t_off $t_off_sd $f16_tg_off $f16_tg_off_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        tg_vs_f16_off="${ratio_val}±${ratio_sd}x"
                    else
                        tg_vs_f16_off="${ratio_val}x"
                    fi
                fi
            fi

            printf "  %-10s %-10s %16s %16s %16s %16s\n" \
                "$k_type" "$v_type" "$pp_vs_f16_on" "$pp_vs_f16_off" "$tg_vs_f16_on" "$tg_vs_f16_off"
        done

        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            printf "  %-10s %-10s %16s %16s %16s %16s\n" \
                "---ref---" "---ref---" "-------" "----------" "------" "---------"
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                local k_disp="ref-${pair%%:*}" v_disp="ref-${pair##*:}"
                local p_on="" t_on="" p_off="" t_off=""
                local p_on_sd="" t_on_sd="" p_off_sd="" t_off_sd=""
                local pp_vs_f16_on="n/a" tg_vs_f16_on="n/a" pp_vs_f16_off="n/a" tg_vs_f16_off="n/a"
                eval "p_on=\${pp_${lvl}[$ref_key]:-}"
                eval "p_on_sd=\${ppsd_${lvl}[$ref_key]:-}"
                eval "t_on=\${tg_${lvl}[$ref_key]:-}"
                eval "t_on_sd=\${tgsd_${lvl}[$ref_key]:-}"
                p_off="${pp_scalar[$ref_key]:-}"
                p_off_sd="${ppsd_scalar[$ref_key]:-}"
                t_off="${tg_scalar[$ref_key]:-}"
                t_off_sd="${tgsd_scalar[$ref_key]:-}"

                if [ -n "$p_on" ] && [ -n "$f16_pp_on" ]; then
                    local ratio_val=$(echo "$p_on $f16_pp_on" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$p_on_sd" ] && [ -n "$f16_pp_on_sd" ]; then
                        local ratio_sd=$(echo "$p_on $p_on_sd $f16_pp_on $f16_pp_on_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        pp_vs_f16_on="${ratio_val}±${ratio_sd}x"
                    else
                        pp_vs_f16_on="${ratio_val}x"
                    fi
                fi
                if [ -n "$t_on" ] && [ -n "$f16_tg_on" ]; then
                    local ratio_val=$(echo "$t_on $f16_tg_on" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$t_on_sd" ] && [ -n "$f16_tg_on_sd" ]; then
                        local ratio_sd=$(echo "$t_on $t_on_sd $f16_tg_on $f16_tg_on_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        tg_vs_f16_on="${ratio_val}±${ratio_sd}x"
                    else
                        tg_vs_f16_on="${ratio_val}x"
                    fi
                fi
                if [ -n "$p_off" ] && [ -n "$f16_pp_off" ]; then
                    local ratio_val=$(echo "$p_off $f16_pp_off" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$p_off_sd" ] && [ -n "$f16_pp_off_sd" ]; then
                        local ratio_sd=$(echo "$p_off $p_off_sd $f16_pp_off $f16_pp_off_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        pp_vs_f16_off="${ratio_val}±${ratio_sd}x"
                    else
                        pp_vs_f16_off="${ratio_val}x"
                    fi
                fi
                if [ -n "$t_off" ] && [ -n "$f16_tg_off" ]; then
                    local ratio_val=$(echo "$t_off $f16_tg_off" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$t_off_sd" ] && [ -n "$f16_tg_off_sd" ]; then
                        local ratio_sd=$(echo "$t_off $t_off_sd $f16_tg_off $f16_tg_off_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        tg_vs_f16_off="${ratio_val}±${ratio_sd}x"
                    else
                        tg_vs_f16_off="${ratio_val}x"
                    fi
                fi

                printf "  %-10s %-10s %16s %16s %16s %16s\n" \
                    "$k_disp" "$v_disp" "$pp_vs_f16_on" "$pp_vs_f16_off" "$tg_vs_f16_on" "$tg_vs_f16_off"
            done
        fi

        echo "=========================================="
    }

    if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
        for lvl in "${COOPMAT_LEVELS[@]}"; do
            print_table "$lvl"
            print_vs_f16_table "$lvl"
        done
    else
        echo ""
        echo "=========================================="
        echo " Results [$cfg] (t/s, mean±stdev)"
        echo "=========================================="

        printf "  %-10s %-10s %7s %16s %16s\n" "K type" "V type" "compr" "pp" "tg"
        printf "  %-10s %-10s %7s %16s %16s\n" "------" "------" "-----" "--" "--"

        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            pp_v="${pp_scalar[$pair]:-n/a}"
            pp_sd="${ppsd_scalar[$pair]:-}"
            tg_v="${tg_scalar[$pair]:-n/a}"
            tg_sd="${tgsd_scalar[$pair]:-}"
            pp_d="$pp_v" tg_d="$tg_v"
            [ -n "$pp_sd" ] && [ "$pp_v" != "n/a" ] && pp_d="${pp_v}±${pp_sd}"
            [ -n "$tg_sd" ] && [ "$tg_v" != "n/a" ] && tg_d="${tg_v}±${tg_sd}"
            compr_disp=""
            if [ "$pair" = "f16:f16" ]; then
                compr_disp="1.00x"
            else
                compr_disp=$(get_compression "$pair")
            fi
            printf "  %-10s %-10s %7s %16s %16s\n" "$k_type" "$v_type" "$compr_disp" "$pp_d" "$tg_d"
        done

        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            printf "  %-10s %-10s %7s %16s %16s\n" "---ref---" "---ref---" "-----" "--" "--"
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                k_disp="ref-${pair%%:*}"
                v_disp="ref-${pair##*:}"
                pp_v="${pp_scalar[$ref_key]:-n/a}"
                pp_sd="${ppsd_scalar[$ref_key]:-}"
                tg_v="${tg_scalar[$ref_key]:-n/a}"
                tg_sd="${tgsd_scalar[$ref_key]:-}"
                pp_d="$pp_v" tg_d="$tg_v"
                [ -n "$pp_sd" ] && [ "$pp_v" != "n/a" ] && pp_d="${pp_v}±${pp_sd}"
                [ -n "$tg_sd" ] && [ "$tg_v" != "n/a" ] && tg_d="${tg_v}±${tg_sd}"
                compr_disp=$(get_compression "$ref_key")
                printf "  %-10s %-10s %7s %16s %16s\n" "$k_disp" "$v_disp" "$compr_disp" "$pp_d" "$tg_d"
            done
        fi

        echo "=========================================="

        echo ""
        echo "=========================================="
        echo " vs f16 Baseline [$cfg]"
        echo "=========================================="

        f16_pp_s="${pp_scalar[f16:f16]:-}"
        f16_tg_s="${tg_scalar[f16:f16]:-}"
        f16_pp_s_sd="${ppsd_scalar[f16:f16]:-}"
        f16_tg_s_sd="${tgsd_scalar[f16:f16]:-}"

        if [ "$HAS_STDEV" -eq 1 ]; then
            printf "  %-10s %-10s %16s %16s\n" "K type" "V type" "pp vs f16" "tg vs f16"
        else
            printf "  %-10s %-10s %12s %12s\n" "K type" "V type" "pp vs f16" "tg vs f16"
        fi
        printf "  %-10s %-10s %16s %16s\n" "------" "------" "---------" "---------"

        for pair in "${ALL_CONFIGS[@]}"; do
            k_type="${pair%%:*}"
            v_type="${pair##*:}"
            if [ "$pair" = "f16:f16" ]; then
                printf "  %-10s %-10s %16s %16s\n" "$k_type" "$v_type" "(baseline)" "(baseline)"
            else
                pp_v="${pp_scalar[$pair]:-}"
                tg_v="${tg_scalar[$pair]:-}"
                pp_sd_v="${ppsd_scalar[$pair]:-}"
                tg_sd_v="${tgsd_scalar[$pair]:-}"
                pp_r="n/a" tg_r="n/a"
                if [ -n "$pp_v" ] && [ -n "$f16_pp_s" ]; then
                    ratio_val=$(echo "$pp_v $f16_pp_s" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$pp_sd_v" ] && [ -n "$f16_pp_s_sd" ]; then
                        ratio_sd=$(echo "$pp_v $pp_sd_v $f16_pp_s $f16_pp_s_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        pp_r="${ratio_val}±${ratio_sd}x"
                    else
                        pp_r="${ratio_val}x"
                    fi
                fi
                if [ -n "$tg_v" ] && [ -n "$f16_tg_s" ]; then
                    ratio_val=$(echo "$tg_v $f16_tg_s" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$tg_sd_v" ] && [ -n "$f16_tg_s_sd" ]; then
                        ratio_sd=$(echo "$tg_v $tg_sd_v $f16_tg_s $f16_tg_s_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        tg_r="${ratio_val}±${ratio_sd}x"
                    else
                        tg_r="${ratio_val}x"
                    fi
                fi
                printf "  %-10s %-10s %16s %16s\n" "$k_type" "$v_type" "$pp_r" "$tg_r"
            fi
        done

        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            printf "  %-10s %-10s %16s %16s\n" "---ref---" "---ref---" "---------" "---------"
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                k_disp="ref-${pair%%:*}"
                v_disp="ref-${pair##*:}"
                pp_v="${pp_scalar[$ref_key]:-}"
                tg_v="${tg_scalar[$ref_key]:-}"
                pp_sd_v="${ppsd_scalar[$ref_key]:-}"
                tg_sd_v="${tgsd_scalar[$ref_key]:-}"
                pp_r="n/a" tg_r="n/a"
                if [ -n "$pp_v" ] && [ -n "$f16_pp_s" ]; then
                    ratio_val=$(echo "$pp_v $f16_pp_s" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$pp_sd_v" ] && [ -n "$f16_pp_s_sd" ]; then
                        ratio_sd=$(echo "$pp_v $pp_sd_v $f16_pp_s $f16_pp_s_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        pp_r="${ratio_val}±${ratio_sd}x"
                    else
                        pp_r="${ratio_val}x"
                    fi
                fi
                if [ -n "$tg_v" ] && [ -n "$f16_tg_s" ]; then
                    ratio_val=$(echo "$tg_v $f16_tg_s" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print "n/a"}')
                    if [ "$HAS_STDEV" -eq 1 ] && [ -n "$tg_sd_v" ] && [ -n "$f16_tg_s_sd" ]; then
                        ratio_sd=$(echo "$tg_v $tg_sd_v $f16_tg_s $f16_tg_s_sd" | awk '{
                            if ($3 > 0) { a=($2/$3)^2; b=($1*$4/($3*$3))^2; printf "%.2f", sqrt(a+b) } else print "0.00"
                        }')
                        tg_r="${ratio_val}±${ratio_sd}x"
                    else
                        tg_r="${ratio_val}x"
                    fi
                fi
                printf "  %-10s %-10s %16s %16s\n" "$k_disp" "$v_disp" "$pp_r" "$tg_r"
            done
        fi

        echo "=========================================="
    fi

    # --- Write CSV rows ---

    if [ -n "$CSV_FILE" ]; then
        ratio() { echo "$1 $2" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}'; }

        f16_pp_scalar="${pp_scalar[f16:f16]:-}"
        f16_tg_scalar="${tg_scalar[f16:f16]:-}"

        for lvl in "${COOPMAT_LEVELS[@]}"; do
            local_label=$(coopmat_label_for "$lvl")
            eval "f16_pp_lvl=\${pp_${lvl}[f16:f16]:-}"
            eval "f16_tg_lvl=\${tg_${lvl}[f16:f16]:-}"

            for pair in "${ALL_CONFIGS[@]}"; do
                k_type="${pair%%:*}"
                v_type="${pair##*:}"
                is_m="no"
                [ "$k_type" != "$v_type" ] && is_m="yes"
                eval "pp_v=\${pp_${lvl}[$pair]:-}"
                eval "pp_sd_v=\${ppsd_${lvl}[$pair]:-}"
                eval "tg_v=\${tg_${lvl}[$pair]:-}"
                eval "tg_sd_v=\${tgsd_${lvl}[$pair]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_lvl")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_lvl")
                pp_vs_scl=$(ratio "$pp_v" "${pp_scalar[$pair]:-}")
                tg_vs_scl=$(ratio "$tg_v" "${tg_scalar[$pair]:-}")
                csv_append "$local_label" "$k_type" "$v_type" "$is_m" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "$pp_vs_scl" "$tg_vs_scl"
            done
        done

        if [ ${#COOPMAT_LEVELS[@]} -eq 0 ] || [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
            for pair in "${ALL_CONFIGS[@]}"; do
                k_type="${pair%%:*}"
                v_type="${pair##*:}"
                is_m="no"
                [ "$k_type" != "$v_type" ] && is_m="yes"
                pp_v="${pp_scalar[$pair]:-}"
                pp_sd_v="${ppsd_scalar[$pair]:-}"
                tg_v="${tg_scalar[$pair]:-}"
                tg_sd_v="${tgsd_scalar[$pair]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_scalar")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_scalar")
                csv_append "scalar" "$k_type" "$v_type" "$is_m" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "" ""
            done
        fi

        if [ ${#REF_CONFIGS[@]} -gt 0 ]; then
            for pair in "${REF_CONFIGS[@]}"; do
                ref_key="ref-${pair%%:*}:ref-${pair##*:}"
                k_disp="ref-${pair%%:*}"
                v_disp="ref-${pair##*:}"
                is_m="no"
                [ "${pair%%:*}" != "${pair##*:}" ] && is_m="yes"
                pp_v="${pp_scalar[$ref_key]:-}"
                pp_sd_v="${ppsd_scalar[$ref_key]:-}"
                tg_v="${tg_scalar[$ref_key]:-}"
                tg_sd_v="${tgsd_scalar[$ref_key]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_scalar")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_scalar")
                csv_append "ref" "$k_disp" "$v_disp" "$is_m" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "" ""
            done
        fi
    fi

    # Clean up per-config associative arrays
    unset pp_scalar tg_scalar ppsd_scalar tgsd_scalar
    for lvl in "${COOPMAT_LEVELS[@]}"; do
        unset "pp_${lvl}" "tg_${lvl}" "ppsd_${lvl}" "tgsd_${lvl}"
    done

done  # end config loop

echo ""
echo "Done. Detected coopmat level: $COOPMAT_LEVEL."
echo "GPU device: $GPU_DEVICE"
if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
    for lvl in "${COOPMAT_LEVELS[@]}"; do
        local_label=$(coopmat_label_for "$lvl")
        echo "Tables compare $local_label (prefill, N>1) vs scalar fallback."
    done
    echo "Speedup > 1.0x indicates coopmat benefit."
else
    echo "No coopmat comparison (either no coopmat support or SKIP_COOPMAT_COMPARE=1)."
fi
if [ -n "$CSV_FINAL" ]; then
    cp "$CSV_FILE" "$CSV_FINAL"
    rm -f "$CSV_FILE"
    echo ""
    echo "=========================================="
    echo " Output files"
    echo "=========================================="
    echo " CSV: $(readlink -f "$CSV_FINAL") (${#CSV_ROWS[@]} rows)"
    echo " Log: $(readlink -f "$LOG_FILE")"
    echo "=========================================="
fi
